// ============================================================
// HACKING PUZZLE — Fallout 3/NV game-accurate implementation
// ============================================================
//
// MECHANICS (verified from official Fallout wiki sources):
// - 32 lines split into two 16-line columns
// - Each line begins with a hex memory address
// - Lines contain words (candidates) interspersed with junk filler
// - All candidate words are the same length (determined by difficulty)
// - 4 attempts before lockout
// - "x/y correct" feedback = letters in CORRECT POSITION only
// - Bracket pairs ([], {}, (), <>) on the same line are clickable easter eggs
// - Bracket effects: removes a dud OR replenishes attempts (50/50 random)
// - "Entry Denied" if bracket clicked when only 1 word remains
// - Selection methods: click word/bracket, OR type the word

// ============================================================
// WORD POOLS BY DIFFICULTY
// ============================================================
const WORD_POOLS = {
  very_easy: { length: 4, count: 5,  words: [
    "BARN","BLOW","BLUE","BOND","BOOM","BURN","CALL","CARE","CASE","CAVE",
    "CITY","CLAN","CLAW","CLUE","COIL","CORE","COST","CREW","DARK","DEAL",
    "DOOM","DUST","EDGE","EYES","FALL","FATE","FEAR","FILE","FIRE","FLAG",
    "FORK","GAIN","GAME","GATE","GRIM","HAND","HEAT","HOPE","IRON","KEEP",
    "LIFE","LINK","LIST","LOCK","LOSS","LOVE","MASK","MIND","NEED","OPEN",
    "PACK","PAIN","PATH","PLAN","REAL","RICH","ROAD","ROCK","ROOM","ROOT",
    "RUIN","RULE","SAFE","SALT","SAND","SEED","SELL","SHED","SHIP","SLOW",
    "SOUL","SPIN","STAR","TASK","TEAM","TIME","TOOL","TOWN","TRAP","UNIT",
    "VAST","VAULT","VOID","WARN","WIND","WIRE","WORD","WORK","ZONE"
  ]},
  easy: { length: 5, count: 8, words: [
    "ABYSS","ADMIN","AGENT","ALERT","ALIVE","ALLOY","ALONE","ANGEL","ARDOR",
    "ARMED","ARROW","BLADE","BLAST","BLOCK","BLOOD","BOARD","BREAD","BRICK",
    "BUNKER","CABLE","CANYON","CHAIN","CIVIL","CLEAR","CLONE","CLOSE","COURT",
    "CRAFT","CRATE","CROWN","DEATH","DEPTH","DIRTY","DRAFT","DREAD","DRIFT",
    "EAGLE","EARTH","EMPTY","EQUIP","ERROR","ETHIC","FALSE","FATAL","FIBER",
    "FIELD","FLAME","FLASH","FORCE","FORTH","FORTY","FROST","GENRE","GLAND",
    "GRAIN","GRAVE","GREAT","GROUP","GUARD","GUILD","GUILT","HEART","HEAVY",
    "HONOR","HOTEL","HOUSE","HUMAN","IDEAL","INNER","JEWEL","JUDGE","KARMA",
    "KEEPS","KEYS","LASER","LATER","LATIN","LEDGE","LIGHT","LIMIT","LIVER",
    "LOCAL","LODGE","LOWER","LOYAL","LUCID","LUNAR","LYING","MACRO","MAGIC",
    "MAJOR","MAYOR","METAL","METER","MICRO","MIGHT","MIXED","MODEL","MORAL",
    "MOTOR","MURKY","NIGHT","NOBLE","NOISE","NORTH","NOVEL","OCEAN","ORBIT",
    "ORDER","OUTER","PANIC","PARTY","PATCH","PAUSE","PEACH","PENNY","PHASE",
    "PILOT","PIONEER","PIVOT","PLANE","PLATE","POINT","POWER","PRICE","PRIME",
    "PRISM","PROOF","PROUD","PUBLIC","PULSE","QUEST","QUICK","QUIET","RADIO",
    "RAIDS","RAVEN","REACT","REALM","RELIC","REPLY","RIDGE","RIGHT","RIVER",
    "ROBOT","ROYAL","RUINED","RURAL","SCRAP","SHADE","SHARP","SHELL","SHIFT",
    "SHIRT","SHOCK","SHORE","SHOUT","SIEGE","SIGHT","SILVER","SIXTY","SKILL",
    "SLAVE","SLEEP","SLICE","SMOKE","SOLID","SPEAK","SPELL","SPENT","SPIKE",
    "SPINE","SPLIT","SPRAY","SPREAD","SQUAD","STAGE","STAKE","START","STATE",
    "STEAM","STEEL","STEEP","STEER","STERN","STING","STOCK","STOLE","STONE",
    "STORM","STORY","STRAY","STRIKE","SUITE","SUPER","SWEAR","SWORD","TANGO",
    "TIGHT","TIRED","TITLE","TOWER","TRACE","TRACK","TRADE","TRAIL","TREND",
    "TRIAL","TRIBE","TRICK","TRUST","TRUTH","UNDER","UNITY","UPPER","USHER",
    "VAGUE","VALID","VAULT","VAGUE","VERSE","VITAL","VOTER","VOWEL","WATCH",
    "WATER","WHEEL","WORLD","WORSE","WORST","WORTH","WRECK","WRIST","WRONG",
    "YOUNG","YOUTH"
  ]},
  average: { length: 6, count: 12, words: [
    "ACCESS","ACCEPT","ACTIVE","ADVICE","AFFAIR","AGENCY","AGREED","ALARMS","ALMOST",
    "ANCHOR","ANSWER","APPEAR","ARCADE","ARMORY","ARMORS","ARRIVE","ARROWS","ASYLUM",
    "ATOMIC","ATTACK","BANISH","BARREL","BATTER","BATTLE","BEACON","BECOME","BEHIND",
    "BELIEF","BETRAY","BIGGER","BINARY","BISHOP","BIZARRE","BLOODY","BORDER","BOTANY",
    "BOTTLE","BOUNTY","BRAVELY","BRIDGE","BRIGHT","BRONZE","BUFFER","BULLET","BUNKER",
    "BURIED","BUTLER","BUTTON","CABINS","CACTUS","CAESAR","CAGED","CALLED","CALMED",
    "CANYON","CANNON","CARBON","CARGO","CARRIE","CASKET","CAUGHT","CAVERN","CEMENT",
    "CENSOR","CENSUS","CENTER","CHAINS","CHANCE","CHANGE","CHARGE","CHASES","CHEERS",
    "CHIEFS","CHOICE","CHURCH","CINDER","CIRCLE","CITIES","CLAIMS","CLEVER","CLOSED",
    "CLOSER","CLOTHS","CLOUDS","COBALT","CODENAME","COFFER","COMMON","COMRADE","CONDOR",
    "COPPER","CORDED","CORNER","COVERED","CRADLE","CRATER","CREDIT","CRIMES","CROWNS",
    "CRUSHED","CURFEW","CURIOUS","DAMAGED","DAMSON","DANCED","DANGER","DARKER","DEACON",
    "DEALER","DEARLY","DEBATE","DECADE","DECIDE","DECREE","DEEPLY","DEFEAT","DEFEND",
    "DEFINE","DELETE","DEMAND","DEPART","DEPTH","DESERT","DETAIL","DEVOTE","DIARY",
    "DIRECT","DISARM","DOCTOR","DOSING","DOZENS","DRAFTY","DRIVER","DURESS","DUSTED",
    "ECHOES","EFFORT","ELDERS","ELEVEN","ELICIT","EMBARK","EMBERS","EMERGE","ENCHANT",
    "ENGAGE","ENIGMA","ENOUGH","ENSURE","EQUITY","ESCAPE","ETHERS","EVENLY","EVENTS",
    "EVOLVE","EXOTIC","EXPECT","EXPERT","EXPIRE","EXTANT","EXTEND","EXTRAS","FACING",
    "FACTOR","FAILED","FALLEN","FAMINE","FANCY","FASTER","FATHER","FATIGUE","FELLOW",
    "FENCED","FERRIED","FERVOR","FILTER","FINEST","FINGER","FINISH","FIRING","FIXING",
    "FLEEING","FLIGHT","FLUTED","FOLDED","FOLDER","FOLLOW","FOREST","FORGED","FORMER",
    "FOSTER","FOURTH","FREELY","FROZEN","FUSION","GADGET","GALAXY","GAMBLE","GASLIT",
    "GATHER","GENTLY","GHOSTS","GHOULS","GIVING","GLOBAL","GOLDEN","GOSSIP","GOTHIC",
    "GOVERN","GRADED","GRASPED","GRAVEL","GRINDS","GROUND","GROWTH","GUIDED","GUILDS",
    "HAMLET","HANDED","HANGAR","HAPPENED","HARMED","HEADED","HEALER","HEARTS","HEAVEN",
    "HELPED","HEROES","HIDDEN","HIGHER","HOLLOW","HONEST","HONORS","HORROR","HOSTILE",
    "HOTELS","HUMBLE","HUNGER","HUNTERS","HURDLE","HURTLE","HUSBAND","HYBRID","ICELAND",
    "IGNITE","IMPACT","IMPORT","IMPOSE","INCITE","INDEED","INDIGO","INFAMY","INFECT",
    "INSANE","INSERT","INSIDE","INSTAR","INTAKE","INTACT","INTEND","INVADE","INVERT",
    "INVITE","INWARD","IODINE","ISLAND","JACKED","JADED","JAGGED","JOINED","JOKING",
    "JUDGES","JUMBLE","JUMPED","JUNGLE","JUNIOR","JURIST","JUSTLY","KEEPER","KENNEL",
    "KETTLE","KICKED","KILLED","KILLER","KINDLY","KINSHIP","KITTEN","KNIGHT","KNIVES",
    "KNOCKS","KNOLLS","KOSHER","LABELS","LACING","LADDER","LAMBED","LAMENT","LANCED",
    "LANDED","LANGUOR","LANTERN","LAPSED","LARDER","LARGER","LASTING","LATELY","LATEST",
    "LATTER","LAUNCH","LAVISH","LAWFUL","LAWYER","LAYERS","LAYING","LEADER","LEAGUE",
    "LEAKED","LEARNT","LEAVES","LEDGER","LEGACY","LEGEND","LEGION","LENDER","LENGTH",
    "LESSEN","LESSER","LESSON","LETHAL","LETTER","LIBELS","LIFTED","LIGHTS","LIMITS",
    "LINKED","LINTEL","LIQUID","LISTED","LISTEN","LITHIUM","LIVELY","LIVING","LOADED",
    "LOANED","LOATHE","LOCATE","LOCKED","LOCKER","LODGED","LODGER","LODGES","LOFTED",
    "LOGGED","LOOKED","LOOSEN","LOOTED","LORDED","LORDLY","LORICA","LOSING","LOTTED",
    "LOUDER","LOUSY","LOVELY","LOVING","LOWERED","LULLED","LUMBER","LUNATIC","LUNGED",
    "MADDER","MAGNET","MAIDEN","MAILED","MAJORS","MAKERS","MAKING","MALICE","MAMMAL",
    "MANAGE","MANDATE","MANGLE","MANIAC","MANNER","MANTRA","MAPLES","MARGIN","MARINE",
    "MARKED","MARKER","MARRED","MARTYR","MARVEL","MASKED","MASTER","MATTER","MATURE",
    "MEANER","MEDDLE","MEDIAN","MEDICAL","MEDIUM","MELODY","MELTED","MEMBER","MEMOIR",
    "MEMORY","MENACE","MENDED","MENTOR","MERELY","MERGED","METHOD","METRIC","MIDDLE",
    "MIDWAY","MIGHTY","MIGRATE","MILDER","MILLED","MIMING","MINCED","MINDED","MINGLE",
    "MINISTER","MINOR","MINUS","MINUTE","MIRROR","MISERY","MISLAY","MISSED","MITTEN",
    "MOLTEN","MOMENT","MONIES","MONITOR","MORALS","MORTAL","MOSTLY","MOTHER","MOTIFS",
    "MOTION","MOTIVE","MOUNTED","MURDER","MUTANT","MUSCLES","MUSEUM","MUSTER","MUTUAL",
    "NABBED","NAMING","NARROW","NATIVE","NEARER","NEEDLE","NETHER","NEURAL","NEUTER",
    "NIGHTLY","NIMBLY","NINTHS","NORMAL","NOTICE","NOTION","NUANCE","NULLED","NUMBER",
    "OBJECT","OBLIGE","OBSCURE","OBTAIN","OBVIOUS","OCEAN","OCCULT","OFFEND","OFFERED",
    "OFFICE","OFFSET","OPENED","OPTION","ORACLE","ORATOR","ORDEAL","ORIGIN","OUSTED",
    "OUTAGE","OUTCRY","OUTLET","OUTPUT","OUTRUN","PACING","PACKAGE","PADDED","PAGING",
    "PAINED","PAIRED","PALACE","PARADE","PARDON","PARENT","PARITY","PARLOR","PARSED",
    "PARTED","PARTLY","PASSED","PASSEL","PASTOR","PAYDAY","PAYING","PEACEFUL","PEAKED",
    "PEDDLE","PELTED","PENMAN","PEOPLE","PERIOD","PERISH","PERMIT","PESTLE","PHRASE",
    "PHYSIC","PICKED","PICKLE","PIDGIN","PIECED","PIETY","PIGEON","PILES","PILGRIM",
    "PILLAR","PILLOW","PILOTS","PINION","PIPING","PISTOL","PITHED","PITTED","PLAGUE",
    "PLANES","PLANET","PLANED","PLAQUE","PLAYED","PLAYER","PLAYING","PLEDGE","PLENTY",
    "POETIC","POINTS","POISON","POKING","POLICE","POLISH","POLITE","POPPED","PORTAL",
    "PORTLY","POSING","POSTED","POUNCE","POURED","POWDER","POWERS","POWWOW","PRAISE",
    "PRAYED","PREACHY","PRECISE","PREFER","PRELIM","PREMIER","PREMISE","PRETEND","PREVAIL",
    "PRIEST","PRIZED","PROFANE","PROFIT","PROMISE","PROMPT","PROPER","PROPHET","PROVED",
    "PROVEN","PUBLIC","PUDDLE","PUGNOSE","PUNCHED","PUNGENT","PURIST","PURITY","PUSHED",
    "PUTTER","PUZZLE","QUAKER","QUARRY","QUARTER","QUEERLY","QUICKER","QUIETLY","QUITTED",
    "RABID","RACING","RADIANT","RADIUS","RAIDER","RAINED","RAISIN","RAMBLE","RAMPED",
    "RANCID","RANDOM","RANGED","RANGER","RANKED","RANTED","RAPING","RAPTOR","RARITY",
    "RASHLY","RATHER","RATING","RATTLE","RAVAGE","RAVEN","RAVINE","RAYING","REACHED",
    "READER","READILY","READING","REALM","REASON","REBEL","RECALL","RECAST","RECEDE",
    "RECENT","RECIPE","RECITE","RECKON","RECTOR","REDDEN","REDIRECT","REDONE","REDUCE",
    "REELED","REFERS","REFINE","REFLEX","REFUGE","REFUND","REFUSE","REFUTE","REGARD",
    "REGIME","REGION","REGRET","REGULAR","REJECT","RELATE","RELAYED","RELEASE","RELIEF",
    "RELISH","RELIVE","REMAIN","REMAKE","REMARK","REMEDY","REMEMBER","REMIND","REMORSE",
    "REMOTE","REMOVE","RENAME","RENDER","RENEW","RENTAL","RENTED","REOPEN","REPAIR",
    "REPEAL","REPEAT","REPENT","REPLAY","REPORT","REPOSE","RESCUE","RESEND","RESENT",
    "RESIDE","RESIGN","RESIST","RESORT","RESTED","RESULT","RESUME","RETAIL","RETAIN",
    "RETIRE","RETORT","RETURN","REUNITE","REVEAL","REVERT","REVIEW","REVISE","REVIVE",
    "REVOLT","REWARD","REWIND","REWORK","RIBBON","RIDDLE","RIDING","RIDGED","RIFLED",
    "RIGGED","RIGHTS","RINSED","RIOTED","RIPENED","RISKED","RISING","RIVERS","ROAMED",
    "ROARED","ROASTING","ROBBED","ROBOTS","ROCKED","ROCKET","RODENT","ROGUES","ROLLED",
    "ROMANS","ROOFED","ROOMED","ROOSTS","ROOTED","ROPING","ROSTER","ROTATE","ROTTED",
    "ROUNDED","ROUTED","ROVING","ROWING","ROYALS","RUBBED","RUDELY","RUFFLED","RUINED",
    "RULING","RUMBLE","RUMORS","RUNWAY","SACRED","SADDLE","SAFETY","SAILED","SAILOR",
    "SALARY","SALMON","SALOON","SALUTE","SAMPLE","SANDED","SANELY","SANITY","SAVAGE",
    "SAYING","SCALED","SCALES","SCANNED","SCARCE","SCARED","SCARRED","SCAVENGE","SCENIC",
    "SCHEME","SCHISM","SCHOOL","SCORN","SCRAPS","SCREEN","SCRIBE","SCRIPT","SCROLL",
    "SCYTHE","SEALED","SEARCH","SEASON","SECOND","SECRET","SECURE","SEDATE","SEEING",
    "SEEKER","SEEMED","SEIZED","SELECT","SELLER","SENATE","SENDER","SENIOR","SENSED",
    "SENSOR","SENTRY","SERIES","SERMON","SERVED","SERVER","SETTLE","SEVERE","SHADOW",
    "SHAKEN","SHAKEN","SHAMED","SHAPED","SHARED","SHARED","SHEARS","SHEILA","SHIELD",
    "SHIFTED","SHINED","SHIVER","SHOOTS","SHORES","SHORTS","SHOULD","SHOUTS","SHOWED",
    "SHOWER","SHOWING","SHREWD","SHRINE","SHRINK","SHROUD","SHUFFLE","SHUTUP","SICKLY",
    "SIDING","SIGHED","SIGNAL","SIGNED","SILENT","SILVER","SIMMER","SIMPLE","SINGER",
    "SINGLE","SINNED","SISTER","SITTER","SIZING","SKATED","SKETCH","SKILLS","SKINNED",
    "SLACK","SLAYED","SLAYER","SLEEPS","SLEEVE","SLIDER","SLIGHT","SLIPPED","SLITHER",
    "SLOWLY","SMALLER","SMARTER","SMELLED","SMILED","SMOOTH","SNAILS","SNAKES","SNATCH",
    "SNIFFED","SNOWED","SOAKED","SOARED","SOCKED","SOFTLY","SOILED","SOLEMN","SOLVED",
    "SORTED","SOUGHT","SOUNDS","SOURCE","SOVIET","SPADES","SPARED","SPEAKS","SPEARS",
    "SPECIAL","SPEEDS","SPELLS","SPENDS","SPHERE","SPILLS","SPIRAL","SPIRIT","SPLITS",
    "SPOILS","SPONGES","SPOOLS","SPORTS","SPOTLIT","SPRANG","SPRAWL","SPREAD","SPRINT",
    "SPYING","SQUADS","SQUARE","STABLE","STAFFS","STAGED","STAINS","STAIRS","STAKES",
    "STALKS","STAMPS","STANDS","STARED","STARRY","STARTS","STATED","STATES","STAYED",
    "STEADY","STEALS","STEAMS","STEELS","STEERS","STELLA","STENCH","STEREO","STERILE",
    "STICKS","STIFLE","STILTS","STINKS","STIRRED","STITCHED","STOCKS","STOLES","STOLEN",
    "STONES","STOOPED","STORED","STORMS","STORMY","STOVES","STOWAGE","STRAIN","STRAND",
    "STRAYED","STREAM","STRETCH","STRICT","STRIDE","STRIKE","STRING","STRIPES","STRIPS",
    "STRIVE","STROKE","STRONG","STRUCK","STRUNG","STUFFED","STUMPS","STYLED","STYLES",
    "SUBDUE","SUBJECT","SUBMIT","SUBPLOT","SUBURB","SUBWAY","SUCKER","SUDDEN","SUFFER",
    "SUGARED","SUITES","SUITED","SULLEN","SULTAN","SUMMER","SUMMON","SUNKEN","SUNNILY",
    "SUNSET","SUPERB","SUPPER","SUPREME","SURELY","SURFER","SURGED","SURVEY","SURVIVE",
    "SUSPECT","SUSTAIN","SWAGGER","SWAYED","SWEATY","SWEEPS","SWEETS","SWELLS","SWERVE",
    "SWORDS","SWORE","SYMBOL","SYRUP","SYSTEM","TACTIC","TAILS","TAINTED","TAKEN",
    "TALENT","TALKED","TAMING","TANGLE","TANKED","TAPPED","TARGET","TARRY","TASKED",
    "TASTED","TATTERED","TATTOO","TAUGHT","TAVERN","TEACHER","TEAMED","TEEMED","TEMPLE",
    "TENANT","TENDED","TENDER","TENSED","TENTHS","TERMS","TERRACE","TERROR","TESTED",
    "TESTING","TESTIFY","THAWED","THEORY","THESE","THIRTY","THORN","THOSE","THREAD",
    "THREAT","THROAT","THRONG","THROWN","THRUST","TICKET","TIDIED","TIERED","TIGERS",
    "TIGHT","TILDE","TILLED","TIMBER","TIMED","TINGLE","TINTED","TINY","TIPPED","TIRADE",
    "TITLED","TOLLED","TOMBED","TONGUE","TOOLED","TOPICS","TOPPED","TORTURE","TOSSED",
    "TOTALS","TOUCH","TOUGH","TOURNEY","TOWERS","TOWING","TOXIC","TRACED","TRACES",
    "TRACKS","TRADED","TRADER","TRAGIC","TRAILS","TRAINED","TRAITOR","TRAMPLE","TRANSIT",
    "TRAPPED","TRASH","TRAVEL","TRAYED","TREADS","TREATED","TREATY","TREND","TRENDS",
    "TRIBAL","TRIBES","TRICKS","TRIED","TRIFLE","TRIM","TRIPLE","TRIUMPH","TROOPS",
    "TROPHY","TROUBLE","TRUCK","TRULY","TRUST","TRUTHS","TURNED","TUTORS","TWELFTH",
    "TWELVE","TWENTY","TWIST","TWISTED","TYRANT","UNABLE","UNCOIL","UNCOVER","UNCURL",
    "UNDONE","UNFAIR","UNFOLD","UNHAPPY","UNIFY","UNIQUE","UNISON","UNITED","UNJUST",
    "UNKIND","UNLIKE","UNLINK","UNLOAD","UNLOCK","UNMASK","UNPAID","UNPICK","UNREAD",
    "UNREAL","UNROLL","UNSAFE","UNSEEN","UNSURE","UNTIE","UNTIL","UNTOLD","UNUSED",
    "UNVEIL","UNWED","UNWED","UNWELCOME","UPDATE","UPHELD","UPHOLD","UPKEEP","UPLAND",
    "UPLOAD","UPPER","UPRISE","UPROAR","UPROOT","UPSCALE","UPSET","UPSIDE","UPTAKE",
    "UPTOWN","URGED","URGENT","URGING","USAGE","USEFUL","USHER","UTMOST","UTOPIA",
    "VACANT","VACATE","VAGUE","VALIANT","VALLEY","VALOR","VALUED","VANITY","VAPOR",
    "VARIED","VAULTS","VECTOR","VEILED","VELVET","VENDOR","VENGEANCE","VENOM","VENTED",
    "VERIFY","VERSES","VESPER","VESSEL","VETOED","VIABLE","VICTOR","VIEWED","VIEWER",
    "VIGIL","VIGOR","VILLA","VILLAIN","VINDICATE","VINTAGE","VIOLET","VIOLENT","VIRGIN",
    "VIRTUE","VIRUS","VISAGE","VISCID","VISIT","VISITED","VISUAL","VITAL","VIVIDLY",
    "VOCABLE","VOCAL","VOICE","VOIDED","VOLLEY","VOLUME","VOTING","VOUCH","VOWED",
    "VOYAGE","WAGES","WAGING","WAILED","WAITED","WALKED","WALKER","WALLED","WANDER",
    "WANTED","WARDEN","WARDER","WARMED","WARMER","WARNED","WARPED","WARRANT","WARRIOR",
    "WASHED","WASTED","WATCHED","WATCHER","WATERED","WAVING","WEAKEN","WEAPON","WEARING",
    "WEARY","WEAVES","WEDGE","WEEPING","WEIGHED","WEIGHT","WELCOME","WELDED","WELDER",
    "WELLED","WHALES","WHARFS","WHEEL","WHEELS","WHILE","WHILED","WHIPPED","WHIRLED",
    "WHIRRED","WHISKEY","WHISPER","WHITE","WHITER","WHOLE","WICKED","WIDELY","WIDER",
    "WIDOWS","WIELDS","WIGGLE","WILDER","WILLED","WILTED","WINDS","WINGED","WINNER",
    "WINTER","WIPED","WIRED","WISDOM","WISELY","WISHED","WITHER","WITHERED","WITNESS",
    "WIZARD","WOODEN","WORDED","WORKED","WORKER","WORLDS","WORRY","WORSEN","WORSHIP",
    "WORSTED","WOUNDS","WRECK","WRECKED","WRENCH","WRESTLE","WRETCH","WRINGS","WRITER",
    "WRITTEN","WRONGED","YANKED","YEARN","YELLED","YIELD","YIELDS","YONDER","ZEALOT",
    "ZEPHYR","ZEROED","ZONING"
  ]},
  hard: { length: 8, count: 16, words: [
    "ABDUCTED","ABRASIVE","ABSCONDED","ABSENTLY","ABSOLUTE","ABSORBED","ABSTRACT","ABUNDANCE",
    "ACADEMIC","ACCEDED","ACCENTED","ACCEPTED","ACCESSED","ACCIDENT","ACCOLADE","ACCOMPLISH",
    "ACCURACY","ACCURATE","ACCUSING","ACETYLENE","ACHIEVED","ACHIEVES","ACQUIRED","ACTIVATE",
    "ADJACENT","ADJOINED","ADJUSTED","ADMIRING","ADMITTED","ADOPTING","ADORABLE","ADRIFT",
    "ADVANCED","ADVANCES","ADVISORY","ADVOCATE","AFFINITY","AFFLICTED","AFFORDED","AGGRIEVED",
    "AILMENTS","AIRBORNE","AIRCRAFT","AIRFIELD","AIRPLANE","ALCOHOLS","ALLEGEDLY","ALLERGIC",
    "ALLIANCE","ALLOTTED","ALLUDING","ALMANACS","ALPHABET","ALTERING","AMBIGUOUS","AMBUSHED",
    "AMENABLE","AMNESIAC","AMPLIFY","AMPUTATE","AMUSEMENT","ANALYSED","ANALYSIS","ANALYZED",
    "ANCESTOR","ANCHORED","ANGLICAN","ANNEXED","ANNOUNCE","ANNOYED","ANOINTED","ANTHEMS",
    "ANTHEMIC","ANTIQUE","ANTIDOTE","ANTITANK","ANXIETY","ANYTHING","ANYWHERE","APPLIED",
    "APPRISED","APPROACH","APPROVAL","APPROVED","APRICOTS","ARGUMENT","ARMORERS","ARMORIES",
    "ARRANGED","ARRESTED","ARRIVALS","ARSENALS","ARSONIST","ARTERIES","ARTHRITIS","ARTICLES",
    "ARTIFACT","ARTILLERY","ARTISANS","ASCENDED","ASCERTAIN","ASCETIC","ASPIRING","ASSAILED",
    "ASSAILANT","ASSASSIN","ASSEMBLE","ASSEMBLY","ASSERTED","ASSESSED","ASSIGNED","ASSISTED",
    "ASSORTED","ASSUMING","ASSURING","ASYMMETRY","ATHEISTS","ATMOSPHERE","ATOMIZED","ATROCITY",
    "ATTACKED","ATTACKER","ATTAINED","ATTEMPTED","ATTENDED","ATTESTED","ATTRACTED","ATTRIBUTE",
    "AUCTIONED","AUDIBLY","AUDITORS","AUSTERITY","AUTHENTIC","AUTHORED","AUTOCRATIC","AUTOMATIC",
    "AVAILABLE","AVENGING","AVERSION","AVIATORS","AVOIDED","AWAKENED","AWAKENING","AWARDED",
    "AWESOME","BACKBONE","BACKDOOR","BACKDROP","BACKLIST","BACKLOAD","BACKLOG","BACKPACK",
    "BACKROOM","BACKSIDE","BACKWARDS","BACKYARD","BAFFLING","BALANCED","BALLOON","BALLROOM",
    "BANDAGED","BANISHED","BANTERED","BAPTISMS","BAPTIZED","BARBARIANS","BARBARIC","BARGAINS",
    "BARRACKS","BARRIERS","BARRELED","BARRENESS","BARRISTER","BASEBALL","BASEMENT","BASKETED",
    "BATHHOUSE","BATTALIONS","BATTERED","BATTLING","BAYONETS","BEARDED","BEATABLE","BEAUTIFY",
    "BECKONED","BEDFRAMES","BEDRIDDEN","BEDROOMS","BEEKEEPER","BEFITTING","BEFRIEND","BEGGED",
    "BEHAVED","BEHEADED","BEHOLDING","BEKNIGHT","BELABOR","BELIEVED","BELIEVER","BELITTLE",
    "BELONGED","BEMOANED","BENEDICT","BENEFITS","BERATED","BEREAVED","BESEECHED","BESIEGED",
    "BESTOWED","BETRAYED","BETROTHED","BEVERAGE","BICYCLES","BIENNIAL","BIGGER","BILLOWED",
    "BIOLOGY","BIRDWATCH","BIRTHDAY","BIRTHED","BISCUIT","BLACKLIST","BLACKLY","BLANCHED",
    "BLANKLY","BLASTING","BLATANT","BLEACHED","BLEEDING","BLEMISHES","BLINDLY","BLISTERED",
    "BLOATED","BLOCKAGE","BLOODIED","BLOOMING","BLOTTED","BLUEPRINT","BLUNDERS","BLUNTLY",
    "BLURRED","BLUSHING","BLUSTER","BOATING","BOLDFACE","BOLSTER","BOMBARDED","BOMBINGS",
    "BONDAGE","BONFIRES","BOOKMARK","BORROWED","BOTANIST","BOTTLES","BOULEVARD","BOUNDED",
    "BOUNTIES","BRACELET","BRADYCARDIAC","BRAINPAN","BRANCHED","BRANDISHED","BRAVADO",
    "BREACHED","BREASTED","BREATHED","BRECKEN","BREEDING","BREEZED","BREVITY","BREWING",
    "BRICKBAT","BRIDLED","BRIEFED","BRIEFER","BRIEFING","BRIGADE","BRIGHTLY","BRIMMING",
    "BRISTLED","BROADCAST","BROADER","BROCHURE","BROILED","BROKERED","BRONZED","BRUSHED",
    "BRUTALITY","BUCCANEER","BUCKLED","BUDGETED","BUFFETED","BUILDING","BULLETED","BULLETIN",
    "BUMPER","BUNGLED","BUOYANT","BURDENED","BURGLARY","BURIALS","BURNINGS","BURNISH",
    "BURROWED","BURSTING","BUSHELED","BUSTLED","BUSYBODY","BUTTRESS","BYSTANDER","CABINETS",
    "CABLED","CACHED","CACKLED","CADAVERS","CALCIFIED","CALCULATE","CALENDAR","CALIBRATE",
    "CALLABLE","CALLED","CALLOUSED","CAMARADERIE","CAMPAIGNS","CAMPFIRES","CAMPGROUND","CANADIAN",
    "CANCELED","CANCEROUS","CANDIDATE","CANINES","CANISTER","CANNIBAL","CANOEISTS","CANTANKEROUS",
    "CANTEENS","CAPACITY","CAPTAINS","CAPTIONED","CAPTIVATE","CAPTURED","CARAVANS","CARBINES",
    "CARDBOARD","CARDINAL","CAREFREE","CAREFULLY","CARELESSLY","CARETAKER","CARGO","CAROUSEL",
    "CARRIAGE","CARTILAGE","CARTRIDGE","CASCADED","CASCADES","CASHIERED","CASKETS","CASUALLY",
    "CASUALTIES","CATALYTIC","CATAPHORIC","CATAPULT","CATEGORICAL","CATHEDRAL","CATHODES",
    "CATTAILS","CAULDRON","CAUSALITY","CAUSEWAY","CAUTERIZE","CAVALIERS","CAVERNS","CAVORTED",
    "CEDARS","CEILINGS","CELEBRATED","CELLARED","CEMETERY","CENSURED","CENTERED","CENTRALIZE",
    "CENTURY","CEREMONIAL","CERTIFY","CESSATION","CHAINED","CHAIRMAN","CHALICED","CHALLENGE",
    "CHAMBERS","CHAMPION","CHANGING","CHANNELS","CHARACTER","CHARCOAL","CHARGED","CHARTERED",
    "CHARTING","CHATTERED","CHECKING","CHEMICALS","CHERISHED","CHEVRONS","CHICKENS","CHILDREN",
    "CHIMNEYS","CHISELED","CHIVALRY","CHLORINE","CHOOSING","CHORTLED","CHRISTMAS","CHRONICLE",
    "CHUCKLED","CINNAMON","CINCHED","CIPHERED","CIRCLED","CIRCUITRY","CITADEL","CITATIONS",
    "CITIZENS","CITRUS","CIVILIAN","CIVILITY","CIVILIZED","CLAIMED","CLAMOR","CLANSMAN",
    "CLARITY","CLASHING","CLASSIC","CLAVICLE","CLEANED","CLEANER","CLEANSED","CLEARING",
    "CLEAVED","CLEAVER","CLEMENT","CLERICAL","CLEVERLY","CLIMBED","CLIMBING","CLINGING",
    "CLINICAL","CLIPPED","CLOAKED","CLOAKING","CLOCKED","CLOSEKNIT","CLOSEUP","CLOTHING",
    "CLOUDED","CLOUDING","CLUBBED","CLUMSILY","CLUSTERED","CLUTCHED","CLUTTER","COASTAL",
    "COBBLED","COBBLER","COBWEBS","COCKADE","COCKED","COCKEYED","COCONUT","COERCED","COFFINS",
    "COGNIZANT","COILING","COINAGE","COLDNESS","COLLATERAL","COLLEAGUE","COLLECTED","COLLECTOR",
    "COLLIDED","COLOMBIAN","COLONELS","COLONIES","COLONIZED","COLOSSAL","COLOSSUS","COLUMNED",
    "COMBATED","COMBATING","COMBINED","COMBUSTED","COMETARY","COMFORTED","COMFORTING","COMICAL",
    "COMMANDED","COMMANDER","COMMENCE","COMMENT","COMMERCE","COMMITTED","COMMITTEE","COMMODITY",
    "COMMONLY","COMMONS","COMMUNAL","COMMUNED","COMMUTED","COMPACTED","COMPANIES","COMPARED",
    "COMPELLED","COMPETED","COMPILED","COMPLAIN","COMPLETE","COMPLEX","COMPLY","COMPONENT",
    "COMPOSED","COMPOSER","COMPRISE","COMPUTED","COMPUTER","COMRADES","CONCEALED","CONCEDED",
    "CONCEIVED","CONCERNED","CONCISE","CONCLUDED","CONCOCT","CONCORD","CONCRETE","CONDEMNED",
    "CONDITION","CONDONED","CONDUCT","CONFERRED","CONFESS","CONFIDENT","CONFIDED","CONFINED",
    "CONFIRMED","CONFISCATE","CONFLICT","CONFORM","CONFOUND","CONFRONT","CONFUSED","CONGEALED",
    "CONGEST","CONJOINT","CONJURED","CONNECT","CONNIVED","CONQUEST","CONSCIENCE","CONSECRATED",
    "CONSENT","CONSERVE","CONSIDER","CONSISTED","CONSOLED","CONSORTED","CONSPIRE","CONSTABLE",
    "CONSTRUE","CONSULTED","CONSUMED","CONTACTED","CONTAINED","CONTEMPT","CONTENTED","CONTEST",
    "CONTEXT","CONTINUE","CONTOURS","CONTRACT","CONTRARY","CONTRIBUTE","CONTROL","CONVENED",
    "CONVERSE","CONVERTED","CONVICTED","CONVINCED","CONVOKED","CONVULSED","COOKING","COORDINATED",
    "COPIOUSLY","COPPERED","COPYBOOKS","CORDIAL","CORDIALITY","CORNERED","CORNERSTONE","CORNFIELD",
    "CORONATED","CORONERS","CORPORAL","CORRECTED","CORRECTLY","CORRELATED","CORRIDORS","CORRODED",
    "CORROSION","CORRUPT","COSMETIC","COSTUMED","COTTAGE","COUNTLESS","COUNTRIES","COUPLED",
    "COURAGE","COURIER","COURSING","COUSIN","COVENANT","COVERED","COWARDLY","COWERED",
    "CRACKLED","CRAFTED","CRAMPED","CRANBERRY","CRANKED","CRASHED","CRAZED","CREAKING",
    "CREATED","CREATING","CREATION","CREATURE","CREDITED","CREDULOUS","CREEPING","CREMATED",
    "CRESCENDO","CREVICE","CRICKETS","CRIMINAL","CRIMSON","CRIPPLED","CRITERIA","CRITICAL",
    "CRITICIZE","CROAKING","CROOKED","CROSSED","CROUCHED","CROWBAR","CROWDED","CRUCIBLE",
    "CRUCIFY","CRUELTY","CRUMBLED","CRUMPLED","CRUNCHED","CRUSADED","CRUSADERS","CRUSHED",
    "CRUSTED","CRYPTIC","CRYSTAL","CUDDLED","CULMINATE","CULPABLE","CULTURED","CUMULATE",
    "CUNNING","CURATED","CURIOUSLY","CURRENT","CURRENTLY","CURSING","CURTAINS","CURTAILED",
    "CUSHIONS","CUSTOMARY","CUSTOMER","CYCLONIC","DABBLING","DAINTY","DAMAGED","DAMASKING",
    "DANGERS","DARKENED","DASTARDLY","DATELINE","DAUGHTER","DAUNTING","DAYDREAM","DAZZLING",
    "DEADENED","DEADLINE","DEADLOCK","DEAFENED","DEALINGS","DEAREST","DEBATED","DEBRIEF",
    "DECEASED","DECEIVED","DECEMBER","DECENTLY","DECEPTION","DECIBEL","DECIDED","DECIDEDLY",
    "DECIMATE","DECIPHER","DECISION","DECISIVE","DECLARED","DECLINED","DECODED","DECREASE",
    "DECREED","DEDICATE","DEDUCING","DEDUCTED","DEEMING","DEEPENED","DEFAMING","DEFEATED",
    "DEFEATER","DEFECTED","DEFENDED","DEFERRED","DEFICIENT","DEFILED","DEFINED","DEFINITE",
    "DEFLATED","DEFORMED","DEFRAYED","DEFROST","DEFTLY","DEFUSED","DEFYING","DEGRADED",
    "DEHYDRATE","DELEGATE","DELETING","DELIBERATE","DELIVERED","DELOCALIZE","DELUDED","DELVED",
    "DEMANDED","DEMEANOR","DEMENTED","DEMISED","DEMOLISH","DEMONIZED","DEMOTING","DENIALS",
    "DENIZENS","DENOTED","DENOUNCE","DENSITY","DENTISTRY","DEPARTED","DEPENDED","DEPICTING",
    "DEPLETED","DEPLOYED","DEPORTED","DEPRAVED","DEPRECATED","DEPRESSED","DEPRIVED","DEPUTIES",
    "DEPUTIZED","DERANGED","DERIVED","DESCEND","DESCRIBE","DESERTED","DESERVED","DESIGNED",
    "DESIGNER","DESIRED","DESPAIR","DESPERATE","DESPISED","DESTINED","DESTITUTE","DETAILED",
    "DETECTING","DETECTOR","DETOUR","DETRIMENT","DEVASTATE","DEVELOP","DEVIATE","DEVISED",
    "DEVOID","DEVOLVED","DEVOURED","DEVOUTLY","DIABOLIC","DIAGNOSE","DIALECTIC","DIALOGUE",
    "DIAMOND","DICTATED","DIDACTIC","DIESELED","DIETED","DIFFRACT","DIFFUSED","DIGESTED",
    "DIGITAL","DIGNIFY","DILATING","DILEMMA","DILIGENT","DILUTED","DIMENSION","DIMINISH",
    "DIRECTED","DIRECTION","DISAGREE","DISALLOW","DISAPPEAR","DISARMED","DISASTER","DISBELIEF",
    "DISCARDED","DISCERN","DISCIPLE","DISCLOSE","DISCOLOR","DISCORD","DISCOUNT","DISCOVER",
    "DISCREDIT","DISCREET","DISDAIN","DISEASE","DISGRACE","DISGUST","DISHONOR","DISMAYED",
    "DISMISSED","DISMOUNT","DISORDER","DISOWN","DISPATCH","DISPELLED","DISPERSE","DISPLAY",
    "DISPOSED","DISPUTED","DISREGARD","DISRESPECT","DISRUPTED","DISSECTED","DISSEMINATE",
    "DISSENTED","DISSOLVED","DISTANCE","DISTANT","DISTINCT","DISTRESS","DISTRIBUTE","DISTRICT",
    "DISTRUST","DISTURBED","DIVERGED","DIVERSE","DIVERTED","DIVIDED","DIVINE","DIVULGED",
    "DOCUMENT","DOLDRUMS","DOMINATE","DONATED","DOOMSDAY","DORMANT","DOSAGES","DOWNFALL",
    "DOWNRIGHT","DOWNTOWN","DOWNTREND","DOWNWARD","DRAFTED","DRAFTING","DRAGGING","DRAGOON",
    "DRAINAGE","DRAINED","DRAMATIC","DRASTIC","DRAUGHT","DRAWBACK","DRAWERS","DREADED",
    "DREAMED","DREARILY","DREDGED","DRENCHED","DRESSED","DREWDOWN","DRIFTED","DRINKERS",
    "DRIPPED","DRIVELING","DRIVEN","DROOPED","DROPPED","DROUGHTS","DROWNED","DRUDGERY",
    "DRUGGED","DRUMMING","DUBIOUS","DUBLINER","DUNGEONS","DURATION","DUTIFUL","DWELLED",
    "DWELLING","DWINDLED","DYNAMIC","DYNAMITE","DYSFUNCT","DYSTROPHIC","EAGERNESS","EARDRUMS",
    "EARLIER","EARNESTLY","EARRINGS","EARTHEN","EASIER","EASTERN","EASTWARD","EATABLE",
    "ECCENTRIC","ECLIPSE","ECONOMIC","ECSTASY","EDITED","EDITORIAL","EDUCATED","EFFECTED",
    "EFFICIENT","EJECTED","ELABORATE","ELDERLY","ELECTED","ELECTRIC","ELEGANCE","ELEMENT",
    "ELEPHANT","ELEVATED","ELEVATOR","ELIMINATE","ELOQUENT","ELUDING","EMACIATED","EMANATE",
    "EMBEDDED","EMBLEM","EMBODIED","EMBRACED","EMBROIDER","EMERGED","EMIGRATE","EMOTIONS",
    "EMPATHY","EMPEROR","EMPHASIS","EMPLOYED","EMULATED","ENABLE","ENACTED","ENAMELED",
    "ENCASED","ENCHANT","ENCIRCLE","ENCLOSED","ENCODE","ENCOUNTER","ENCROACH","ENCRUSTED",
    "ENCUMBER","ENDANGER","ENDEAVOR","ENDED","ENDLESS","ENDORSE","ENDOWED","ENDURING",
    "ENERGETIC","ENERGIZE","ENFORCED","ENGINEER","ENGRAVED","ENGROSSED","ENHANCED","ENJOYED",
    "ENLARGED","ENLISTED","ENORMOUS","ENRAGED","ENRICHED","ENROLLED","ENSHRINED","ENSLAVED",
    "ENSURED","ENTAILED","ENTANGLE","ENTERED","ENTERING","ENTHRALL","ENTHUSE","ENTIRELY",
    "ENTITLE","ENTITY","ENTRANCE","ENTREATED","ENTRENCH","ENVELOPED","ENVIABLE","ENVIRONED",
    "ENVISAGE","ENVISION","ERECTED","ERODING","ERRANT","ERRATIC","ERUPTED","ERUPTION",
    "ESCALATED","ESCAPED","ESCORTED","ESPIONAGE","ESPOUSED","ESSENTIAL","ESTATES","ESTEEMED",
    "ESTIMATE","ESTRANGED","ETCHING","ETERNAL","EUPHORIA","EVACUATE","EVADED","EVALUATE",
    "EVAPORATE","EVENING","EVENTUAL","EVERYBODY","EVERYDAY","EVERYONE","EVERYTHING","EVERYWHERE",
    "EVICTED","EVIDENCE","EVIDENT","EVOLVED","EXACTLY","EXALTED","EXAMINE","EXAMINED",
    "EXAMPLE","EXCAVATE","EXCEEDED","EXCELLED","EXCEPT","EXCERPT","EXCESSIVE","EXCHANGE",
    "EXCITED","EXCITING","EXCLUDED","EXCLUSIVE","EXECUTE","EXECUTOR","EXEMPLAR","EXEMPTED",
    "EXERCISED","EXHAUSTED","EXHORTED","EXISTED","EXOTIC","EXPANDED","EXPECTED","EXPELLED",
    "EXPENDED","EXPENSE","EXPERIMENT","EXPIRED","EXPLAIN","EXPLICIT","EXPLODED","EXPLOITED",
    "EXPLORED","EXPLORER","EXPORTED","EXPOSED","EXPOSURE","EXPOUND","EXPRESS","EXPUNGED",
    "EXTEND","EXTENDED","EXTENSIVE","EXTERIOR","EXTERMINATE","EXTERNAL","EXTINCT","EXTOLLED",
    "EXTORTED","EXTRACT","EXTREMELY","EXUDED","EYEBROWS","EYELASHES","EYESIGHT","EYEWITNESS",
    "FABRICATE","FACETIOUS","FACELESS","FACETS","FACILITY","FACTUAL","FACULTY","FADING",
    "FAILURES","FAINTED","FAIRGROUND","FAITHFUL","FALLING","FALSEHOOD","FALSIFIED","FALTERED",
    "FAMILIAR","FAMINES","FANATICS","FANCIFUL","FANNING","FANTASY","FARMHOUSE","FARMLAND",
    "FARMYARD","FASCIST","FASHIONED","FASTENED","FASTING","FATALISM","FATALITY","FATEFUL",
    "FATHERED","FATHOMED","FATIGUED","FATTENED","FAULTING","FAVORED","FAVORITE","FEARFUL",
    "FEARLESS","FEASIBLE","FEASTING","FEATHERED","FEATURED","FEEBLE","FELICITY","FELLOWS",
    "FERMENTED","FEROCITY","FERRIED","FERTILIZE","FERVENTLY","FESTERED","FESTIVAL","FETCHED",
    "FETTERED","FEVERISH","FIDELITY","FIENDISH","FIFTIETH","FIGHTERS","FIGHTING","FIGURED",
    "FILAMENT","FILTERED","FINALIST","FINALIZE","FINANCE","FINDINGS","FINISHED","FIREBALL",
    "FIREBASE","FIRELESS","FIREPROOF","FIREWALL","FIREWOOD","FIREWORKS","FISHERMAN","FISHHOOK",
    "FITTINGS","FIXATING","FIXTURE","FLAGGING","FLAGRANT","FLAILED","FLAMETHROWER","FLAMINGO",
    "FLAMMABLE","FLANKED","FLAPPING","FLASHED","FLASHING","FLASHING","FLATBED","FLATHEAD",
    "FLATTENED","FLATTERED","FLAVORED","FLAWLESS","FLEDGED","FLEECED","FLEETED","FLESHED",
    "FLEXIBLE","FLICKERED","FLIGHTLESS","FLIMSIER","FLINCHED","FLINGS","FLINTING","FLIPPED",
    "FLOATED","FLOCKED","FLOGGED","FLOODED","FLOORED","FLOPPED","FLORID","FLOUNCED",
    "FLOWERED","FLUENTLY","FLURRIED","FLUSHED","FLUSTERED","FLUTTERED","FOAMED","FOCUSED",
    "FOLDED","FOLLOW","FOLLOWED","FOLLOWERS","FOLLOWING","FOMENTED","FOOLISH","FOOTBALL",
    "FOOTNOTES","FOOTPATH","FOOTPRINT","FOOTSTEP","FOOTWEAR","FORAGED","FORBIDDEN","FORCEFUL",
    "FORCIBLY","FOREARMS","FOREBODE","FOREBORN","FORECAST","FOREFOOT","FOREFRONT","FOREGOER",
    "FOREGONE","FOREHEAD","FOREIGN","FORENAME","FORENSIC","FOREORDAINED","FORESAW","FORESEE",
    "FORESEEN","FORESHADOW","FORESIGHT","FORESTRY","FORETOLD","FOREVER","FORFEIT","FORGED",
    "FORGETTING","FORGIVEN","FORGOTTEN","FORLORN","FORMALITY","FORMATION","FORMULATE","FORSAKEN",
    "FORTIFIED","FORTNIGHT","FORTRESS","FORTUITOUS","FORTUNATE","FORWARDED","FOSTERED","FOUNDATION",
    "FOUNDERED","FOURFOLD","FOXHOLES","FRACTIONS","FRACTURED","FRAGILE","FRAGMENTED","FRAGRANT",
    "FRAMEWORK","FRANCISCO","FRANKLY","FRANTIC","FRAUDULENT","FRECKLES","FREEHAND","FREELOAD",
    "FREEZING","FRENZIED","FREQUENT","FRESHEST","FRETTED","FRICTION","FRIENDLIER","FRIGHTEN",
    "FRIGIDLY","FRINGED","FRISKILY","FRIVOLITY","FROLICKED","FRONTING","FRONTLINE","FROSTED",
    "FROTHED","FROWNED","FROZEN","FRUITFUL","FRUITION","FRUITLESS","FRUSTRATE","FUELED",
    "FUGITIVE","FULFILLED","FUMBLED","FUMED","FUNCTION","FUNDAMENTAL","FUNDED","FUNNILY",
    "FURIOUS","FURLOUGH","FURNACED","FURNISHED","FURNITURE","FURTIVE","FURTHERED","FURTHERING",
    "GADGETS","GAINED","GAINING","GALLANT","GALLERY","GALLON","GALLOP","GAMBLE","GAMBLED",
    "GANGWAY","GAPING","GARBAGED","GARDENS","GARGLED","GARGOYLE","GARNERED","GARNISHED",
    "GARRISON","GARROTTED","GASOLINE","GASPED","GATEPOST","GATEWAY","GATHERED","GATHERING",
    "GAUZED","GAZING","GEARING","GEMSTONE","GENERAL","GENERATE","GENERATION","GENEROUSLY",
    "GENTLY","GENUFLECT","GENUINE","GEOMETRIC","GERMINATE","GERONIMO","GIBBERED","GIDDINESS",
    "GIFTING","GIGABYTE","GIGGLED","GINGERLY","GIRDLED","GLACIAL","GLADDEN","GLAMOROUS",
    "GLANCED","GLANCING","GLEAMED","GLEANED","GLIDING","GLIMMER","GLIMPSED","GLINTED",
    "GLISTEN","GLITTER","GLOBULES","GLOOMILY","GLORIFY","GLORIOUS","GLOSSED","GLOWED",
    "GLOWERED","GLOWING","GLUTTON","GNASHED","GNAWED","GNAWING","GOATHERD","GOBLET",
    "GOITERED","GOLDFISH","GOLDMINE","GOLFERS","GOSSIPED","GOSSIPER","GOVERNED","GRABBED",
    "GRACEFUL","GRADIENT","GRADUATE","GRAFTED","GRAINED","GRANDCHILD","GRANDIOSE","GRANITE",
    "GRANTED","GRANULAR","GRAPHIC","GRAPPLED","GRASPED","GRASPING","GRATEFUL","GRATIFY",
    "GRAVELED","GRAVITY","GRAYNESS","GRAZED","GREATEST","GREATLY","GREEDY","GREENERY",
    "GRIDIRON","GRIEVED","GRIEVING","GRIM","GRIMACED","GRIMNESS","GRIMY","GRINDER","GRINDING",
    "GRINNED","GRIPPED","GROANED","GROCERS","GRONIC","GROOVED","GROOVES","GROPED","GROUND",
    "GROUNDED","GROUPED","GROUSED","GROWING","GROWLED","GROWLING","GRUDGED","GRUDGING",
    "GRUFFLY","GRUMBLED","GRUMPIER","GRUNTED","GUARANTY","GUARDED","GUARDS","GUERRILLA",
    "GUESSED","GUFFAWED","GUIDED","GUIDING","GUILTILY","GUILTY","GUITAR","GULPING","GUNFIRE",
    "GUNNING","GUNPOWDER","GURGLED","GUSHED","GUSTILY","GUTTERED","GUTTURAL","GUZZLED",
    "GYRATING","HABITS","HACKED","HACKER","HAGGARD","HAGGLED","HAILED","HALLOWED","HALLOWS",
    "HALLWAY","HALTING","HAMLETED","HAMMERED","HAMPERED","HANDBAGS","HANDBALL","HANDFUL",
    "HANDIWORK","HANDLED","HANDLES","HANDSHAKE","HANDSOME","HANDWORK","HANGAR","HANGED",
    "HANKIES","HAPHAZARD","HAPLESS","HAPPENED","HAPPENING","HAPPINESS","HARANGUE","HARASS",
    "HARBORED","HARDIER","HARDIHOOD","HARDLINE","HARDLY","HARDNESS","HARDSHIP","HARDWARE",
    "HARDWORK","HARKEN","HARLEQUIN","HARMFUL","HARMING","HARMLESSLY","HARNESSED","HARPING",
    "HARROWED","HARSHLY","HARVESTED","HASTILY","HATCHED","HATCHET","HATEFULLY","HATEFULNESS",
    "HATTERS","HAUGHTY","HAUNTED","HAUNTING","HAVOCKED","HAYRIDE","HAZARDED","HAZARDOUS",
    "HEADACHE","HEADBAND","HEADGEAR","HEADHUNT","HEADLAMP","HEADLAND","HEADLESS","HEADLINE",
    "HEADQUARTER","HEADREST","HEADROOM","HEADSCARF","HEADSET","HEADSHIP","HEADWAY","HEALED",
    "HEALING","HEAPING","HEARSAY","HEARTACHE","HEARTBEAT","HEARTBROKE","HEARTFELT","HEARTHED",
    "HEARTILY","HEARTLAND","HEARTLESS","HEATED","HEATING","HEATHEN","HEATHEN","HEATHENISH",
    "HEATWAVE","HEAVENLY","HEAVENS","HEAVILY","HEDGED","HEEDED","HEEDFUL","HEEDLESS","HEFTED",
    "HEIGHTEN","HEIGHTH","HEIRLOOM","HELPFUL","HELPING","HELPLESS","HEMORRHAGE","HENCEFORTH",
    "HERALDED","HERBAL","HERBICIDES","HERETOFORE","HERITAGE","HEROIC","HEROISM","HERRING",
    "HESITANT","HESITATE","HEXAGONAL","HEYDAYS","HIBERNATE","HIDDEN","HIDEOUSLY","HIDEOUTS",
    "HIDEOUT","HIDING","HIGHBROW","HIGHCHAIR","HIGHEST","HIGHLIGHT","HIGHWAY","HIJACKED",
    "HILARITY","HILLBILLY","HILLOCKS","HILLSIDE","HINDERED","HINDRANCE","HINDSIGHT","HINTED",
    "HINTING","HISTORIC","HOARDED","HOARDING","HOBBLED","HOBNAILS","HOCKED","HOEING","HOISTED",
    "HOLDFAST","HOLIDAY","HOLLAND","HOLLOWED","HOLOTAPE","HOLSTER","HOMECOMING","HOMELAND",
    "HOMELIKE","HOMEMADE","HOMESPUN","HOMESTEAD","HOMETOWN","HOMEWARD","HOMEWORK","HOMICIDE",
    "HONESTLY","HONEYBEE","HONEYCOMB","HONORARY","HONORED","HOODED","HOODLUM","HOODWINK",
    "HOOKED","HOOKWORM","HOOLIGAN","HOOPLA","HOOTED","HOPEFUL","HOPELESSLY","HOPELESS",
    "HOPSCOTCH","HORDE","HORIZON","HORMONE","HORNETS","HOROSCOPE","HORRENDOUS","HORRIBLY",
    "HORRIFIC","HORRIFIED","HORROR","HORSEBACK","HORSEMAN","HORSESHOE","HOSPITAL","HOSTAGE",
    "HOSTEL","HOSTILE","HOSTLED","HOTBOXED","HOTHEAD","HOTSHOT","HOTTER","HOUNDED","HOURGLASS",
    "HOURLY","HOUSEHOLD","HOUSEKEEP","HOUSING","HOVELS","HOVERED","HOVERING","HOWLING","HUDDLED",
    "HUFFED","HUGGED","HUMANIST","HUMANIZE","HUMANLY","HUMBLY","HUMDRUM","HUMIDITY","HUMILIATE",
    "HUMILITY","HUMORED","HUMORLESS","HUMOROUS","HUMPED","HUNCHED","HUNGERED","HUNGRILY",
    "HUNGRY","HUNTERS","HUNTING","HURDLED","HURLED","HURRICANE","HURRIED","HURRIES","HURTING",
    "HUSBANDS","HUSHED","HUSKED","HUSTLED","HYACINTH","HYDRATED","HYDRAULIC","HYDROGEN",
    "HYGIENIC","HYMNALS","HYPERBOLE","HYPHEN","HYPNOSIS","HYPOTHESIS","ICEBERG","ICEHOUSE",
    "IDENTIFY","IDENTITY","IDEOLOGY","IDIOTIC","IDLENESS","IDOLIZE","IGNITED","IGNOBLY",
    "IGNORANT","IGNORE","IGNORED","ILLEGAL","ILLEGIBLY","ILLNESS","ILLOGICAL","ILLUMINATE",
    "ILLUSION","ILLUSORY","ILLUSTRATED","IMAGINED","IMBIBE","IMITATED","IMMACULATE","IMMERSE",
    "IMMORAL","IMMORTAL","IMMOVABLE","IMPACTED","IMPASSE","IMPATIENT","IMPEACHED","IMPEDED",
    "IMPENDED","IMPERIAL","IMPERVIOUS","IMPLEMENT","IMPLICATE","IMPLIED","IMPLORED","IMPLOSION",
    "IMPORTED","IMPOSED","IMPOSING","IMPOSTOR","IMPOTENT","IMPOUNDED","IMPRESS","IMPRINT",
    "IMPRISON","IMPROBABLE","IMPROMPTU","IMPROPER","IMPROVED","IMPROVISE","IMPULSED","IMPULSIVE",
    "INAUDIBLE","INBORN","INBOUND","INCANDESCENT","INCENSE","INCENTIVE","INCEPTION","INCESSANTLY",
    "INCHWORM","INCIDENT","INCISION","INCITED","INCLINED","INCLOSURE","INCLUDED","INCLUSIVE",
    "INCOMING","INCREASE","INCREDIBLE","INCURRED","INDECENT","INDEPENDENT","INDEXING","INDICATED",
    "INDICTED","INDIRECTLY","INDOOR","INDORSE","INDUCED","INDULGED","INDUSTRY","INEPTLY",
    "INESCAPABLE","INFANT","INFANTRY","INFECTED","INFERIOR","INFERRED","INFERNAL","INFESTED",
    "INFINITE","INFIRMITY","INFLAMED","INFLATED","INFLEXIBLE","INFLICTED","INFLUENCE","INFORMED",
    "INFRARED","INFRINGED","INGENIOUS","INGRAINED","INHABIT","INHALED","INHERIT","INHIBITED",
    "INHUMANE","INITIATED","INJECTED","INJURED","INJURIES","INJUSTICE","INKLINGS","INLAYED",
    "INLAND","INMATES","INNARDS","INNATELY","INNER","INNERMOST","INNINGS","INNKEEPER","INNOCENT",
    "INNOVATED","INPUTTED","INQUEST","INSANELY","INSANITY","INSCRIBE","INSECTS","INSECURE",
    "INSERTED","INSIDIOUS","INSIGHT","INSISTED","INSOLENCE","INSOLUBLE","INSOMNIA","INSPECT",
    "INSPIRED","INSTALL","INSTANCE","INSTEAD","INSTIGATE","INSTILL","INSTINCT","INSTITUTE",
    "INSTRUCT","INSTRUMENT","INSULATE","INSULTED","INSURED","INTACT","INTAKE","INTEGRAL",
    "INTEGRATE","INTEGRITY","INTELLECT","INTENDED","INTENT","INTENTLY","INTERACT","INTERCEDE",
    "INTERCEPT","INTEREST","INTERIOR","INTERLOPER","INTERMENT","INTERN","INTERPRET","INTERROGATE",
    "INTERRUPT","INTERVENED","INTIMATED","INTIMIDATE","INTOLERANT","INTONED","INTREPID","INTRICATE",
    "INTRIGUED","INTRUDED","INTRUSIVE","INTRUSTED","INVADED","INVARIANT","INVASIVE","INVENTED",
    "INVENTORY","INVERTED","INVESTED","INVIDIOUS","INVITED","INVOLVED","INWARDS","IODIZED",
    "IRONED","IRONICAL","IRONWORK","IRONY","IRRATIONAL","IRREGULAR","IRRELEVANT","IRRITATE",
    "ISLANDS","ISOLATED","ITEMIZED","ITINERANT","JABBED","JACKETED","JAILED","JAMMED",
    "JANGLED","JANITORS","JANUARY","JARRED","JAUNDICE","JAUNTED","JAVELIN","JAYWALKED",
    "JEALOUSY","JEERED","JEOPARDY","JESTERED","JETSTREAM","JIGSAWED","JINGLES","JOBBED",
    "JOCULAR","JOGGING","JOINTED","JOKINGLY","JOLLITY","JOSTLED","JOURNAL","JOURNEYED",
    "JOYFUL","JOYRIDE","JUBILANT","JUDGED","JUDGMENT","JUGGLED","JUGGLER","JUICED","JUMBLED",
    "JUMPED","JUMPER","JUNCTION","JUNGLES","JUNIORS","JUNIPER","JURISTED","JUSTIFY","KEEPER",
    "KEEPSAKE","KENNELED","KEPTNESS","KERCHIEF","KERNELED","KESTREL","KEYBOARD","KEYNOTE",
    "KEYSTONE","KICKBACK","KICKED","KIDNAPPED","KILLINGS","KILOMETER","KIMONO","KINDLED",
    "KINDLY","KINDNESS","KINGSHIP","KINSFOLK","KINSHIP","KISSED","KISSING","KITCHENS",
    "KITTEN","KNAPSACK","KNEELED","KNEELING","KNIFED","KNIFING","KNIGHTLY","KNITTED","KNITTER",
    "KNOTTED","KNOWING","KNOWLEDGE","LABELED","LABORED","LABORERS","LABRADOR","LACERATE",
    "LACQUERED","LADDERS","LADYLIKE","LAGGED","LAMENT","LAMENTED","LAMINATE","LANDFALL",
    "LANDFILL","LANDLOCK","LANDLORD","LANDMARK","LANDOWN","LANDSCAPE","LANDSLIDE","LANGUAGE",
    "LANGUID","LANGUISH","LANTERN","LAPSED","LARDER","LARGER","LARGEST","LARYNX","LASCIVIOUS",
    "LASHING","LASTING","LASTLY","LATCHED","LATELY","LATEST","LATTICED","LAUDED","LAUGHED",
    "LAUGHING","LAUGHTER","LAUNCHED","LAUNDRY","LAVENDER","LAVISH","LAWBREAKER","LAWFULLY",
    "LAWMAKER","LAWSUIT","LAYAWAY","LAYERED","LAYOUT","LEAFED","LEAFLET","LEAGUED","LEAKED",
    "LEANNESS","LEAPING","LEARNED","LEARNING","LEASED","LEASHED","LEATHER","LEAVING","LECTURED",
    "LEDGER","LEFTOVER","LEFTWARD","LEGALITY","LEGALIZE","LEGENDARY","LEGGINGS","LEGIBLY",
    "LEGIONS","LEGISLATE","LEGROOM","LEISURED","LEMONADE","LENDABLE","LENGTHEN","LENIENT",
    "LEOPARDS","LESIONS","LESSENED","LESSONS","LETHALLY","LETTERED","LETTUCED","LEVERAGE",
    "LEVITATE","LIABLE","LIAISON","LIBELED","LIBERAL","LIBERATE","LIBERTY","LIBRARIAN","LICENSED",
    "LICKING","LIFEBLOOD","LIFEBOAT","LIFEGUARD","LIFELESS","LIFELIKE","LIFELINE","LIFELONG",
    "LIFETIME","LIFTING","LIGHTED","LIGHTLY","LIGHTNESS","LIGHTNING","LIKEABLE","LIKELINESS",
    "LIKENED","LIKEWISE","LIMBERED","LIMERICK","LIMESTONE","LIMITED","LIMPING","LINEAGE",
    "LINGERED","LINGERING","LINGUIST","LINIMENT","LINKAGES","LIONIZE","LIPSTICKED","LIQUIDED",
    "LISTENED","LISTING","LISTLESS","LITERAL","LITERARY","LITIGATE","LITTERED","LIVABLE",
    "LIVELIHOOD","LIVELIER","LIVENED","LIVERIES","LOADING","LOAFERS","LOATHED","LOATHESOME",
    "LOBBIED","LOBBYIST","LOCALIZED","LOCATED","LOCKED","LOCKERS","LOCKETS","LOCKSMITH",
    "LOCKSTEP","LOCOMOTIVE","LODESTAR","LODGED","LODGINGS","LOGGED","LOGGING","LOITERED",
    "LOITERING","LOLLED","LONELIER","LONELINESS","LONELY","LONGED","LONGER","LONGEST","LONGINGS",
    "LONGITUDE","LOOKOUT","LOOPED","LOOSENED","LOOSER","LOOTED","LOPED","LOPSIDED","LORDLINESS",
    "LORDSHIP","LORICA","LOSING","LOTIONED","LOTTERY","LOUDLY","LOUDNESS","LOUNGED","LOUNGING",
    "LOVABLE","LOVELESS","LOVELIER","LOVELINESS","LOWBORN","LOWERED","LOWNESS","LOYALIST",
    "LOYALLY","LOYALTY","LUCRATIVE","LUDICROUS","LUGGAGE","LUMBERED","LUMINESCE","LUMINOUS",
    "LUNATICS","LUNCHEON","LUNGED","LUSCIOUS","LUSTILY","LUSTROUS","LUTHERAN","LUXURIOUS",
    "LUXURY","LYCANTHROPE","LYNCHING","MACHINED","MACHINIST","MACKEREL","MADHOUSE","MADRIGALS",
    "MAESTRO","MAGAZINE","MAGENTA","MAGGOTS","MAGICAL","MAGNATE","MAGNETIZED","MAGNIFIED",
    "MAGNIFIES","MAGNOLIA","MAHOGANY","MAIDENLY","MAINFRAME","MAINLAND","MAINSTAY","MAINTAIN",
    "MAJESTIC","MAJESTY","MAJOR","MAJORED","MAKEABLE","MAKEDOWN","MAKESHIFT","MAKEUPS",
    "MALADIES","MALADJUST","MALAISE","MALARIA","MALEFACTOR","MALEVOLENT","MALFEASANCE","MALFORMED",
    "MALFUNCTION","MALICIOUS","MALIGNANT","MALINGER","MALPRACTICE","MAMMALIAN","MAMMOTH","MANAGED",
    "MANAGEMENT","MANAGER","MANDARIN","MANDATED","MANDATORY","MANEUVERED","MANGER","MANGROVE",
    "MANHANDLE","MANHOLE","MANIACAL","MANIFEST","MANIFESTO","MANIFOLD","MANIPULATE","MANKIND",
    "MANLINESS","MANNERED","MANSIONED","MANTLED","MANUALLY","MANUFACTURE","MARAUDED","MARBLED",
    "MARCHED","MARCHING","MARGINAL","MARIGOLD","MARINER","MARITIME","MARKEDLY","MARKETED",
    "MARKINGS","MAROONED","MARRIAGE","MARRIED","MARSHAL","MARTIAL","MARTYRDOM","MARTYRED",
    "MARVELED","MARVELOUS","MASKED","MASKING","MASQUERADE","MASSACRE","MASSAGED","MASSED",
    "MASSING","MASTERED","MASTERFUL","MASTERMIND","MASTERY","MATERIAL","MATERNAL","MATHEMATIC",
    "MATTERED","MATURING","MATURITY","MAUNDERED","MAUSOLEUM","MAVERICK","MAYORS","MEANDER",
    "MEANINGFUL","MEANNESS","MEANTIME","MEASURED","MEASURING","MECHANIC","MEDALION","MEDDLED",
    "MEDIATED","MEDICATED","MEDICINE","MEDIEVAL","MEDIOCRITY","MEDITATED","MEDIUM","MEEKLY",
    "MEEKNESS","MEETING","MEGAPHONE","MELANCHOLY","MELODIC","MELTING","MEMBERED","MEMBRANED",
    "MEMENTO","MEMORIZED","MENACED","MENACING","MENDED","MENDING","MENTIONED","MENTORED",
    "MERCHANT","MERCIFUL","MERCILESS","MERCURY","MERGED","MERGING","MERIDIAN","MERITED",
    "MERITED","MESHED","MESSAGED","MESSENGER","MESSIER","METALLIC","METAMORPHIC","METAPHYSICAL",
    "METEORED","METHODICAL","METICULOUS","MICROCHIP","MICROCOSM","MICROFILM","MICROSCOPE",
    "MICROWAVED","MIDDLE","MIDLAND","MIDNIGHT","MIDPOINT","MIDSTREAM","MIDSUMMER","MIDWAY",
    "MIDWESTERN","MIGHTIEST","MIGHTILY","MIGRATED","MILDNESS","MILEPOST","MILITANT","MILITARY",
    "MILITIA","MILLIGRAM","MILLIONS","MILLIPEDE","MIMICKED","MINARET","MINCED","MINDFUL",
    "MINEFIELD","MINGLED","MINIATURE","MINIMUM","MINISTER","MINORED","MINORITY","MINSTRELS",
    "MINTED","MIRACLE","MIRRORED","MISADVENTURE","MISALIGNED","MISBEHAVED","MISCOUNT","MISDEED",
    "MISDIRECT","MISERABLE","MISERLY","MISERY","MISFIRED","MISGUIDED","MISHAP","MISJUDGE",
    "MISLAID","MISLEADING","MISLED","MISMANAGE","MISMATCH","MISNOMER","MISPLACED","MISPRINT",
    "MISPRONOUNCE","MISQUOTE","MISREAD","MISSILED","MISSING","MISSION","MISSPELL","MISSPENT",
    "MISSTATE","MISTAKING","MISTREATED","MISTRESS","MISTY","MISUNDERSTAND","MITIGATE","MIXTURE",
    "MOANING","MOBBED","MOBILIZED","MOCKED","MOCKERY","MODELED","MODERATE","MODERNIZE","MODESTY",
    "MODIFY","MODISTE","MODULATE","MOISTLY","MOISTNESS","MOLDABLE","MOLDED","MOLLIFIED","MOLTED",
    "MONARCH","MONARCHY","MONASTERY","MONETARY","MONEYBOXES","MONITORED","MONOCHROME","MONOGRAMMED",
    "MONOGRAPH","MONOMANIA","MONOPOLY","MONSTERS","MONSTROUS","MONTAGES","MONTHLY","MONUMENT",
    "MOODILY","MOONBEAMS","MOONLIGHT","MOONSHINED","MOORED","MOORING","MOPPED","MORALITY","MORALLY",
    "MORBID","MOREOVER","MORIBUND","MORNINGS","MORONIC","MORTALLY","MORTGAGED","MORTIFIED","MOSAIC",
    "MOSQUITO","MOSSED","MOSTLY","MOTHERED","MOTHERHOOD","MOTHERLY","MOTHPROOF","MOTIONED","MOTIVATE",
    "MOTLEY","MOTOR","MOTORBOAT","MOTORCYCLE","MOTORING","MOTTLED","MOULDED","MOUNTAINS","MOUNTED",
    "MOURNED","MOURNFUL","MOURNING","MOUSED","MOUSETRAPPED","MOUTHED","MOUTHPIECE","MOVABLE",
    "MOVEMENT","MOVIES","MOWED","MUCKED","MUDDIED","MUDDLED","MUFFLED","MUGGED","MUGGLE","MULLED",
    "MULTIFOLD","MULTIPLEX","MULTIPLE","MULTIPLIED","MULTIPLYING","MULTITUDE","MUMBLED","MUMMIFIED",
    "MUNCHED","MUNCHING","MUNDANE","MUNICIPAL","MUNIFICENT","MURDEROUS","MURMURED","MUSEUMS",
    "MUSHROOMED","MUSICAL","MUSICIAN","MUSKETED","MUSTACHE","MUSTAINED","MUSTERED","MUTAGEN",
    "MUTANT","MUTATED","MUTILATE","MUTINIED","MUTTERED","MUTUALITY","MUTUALLY","MUZZLED","MYSTICAL",
    "MYSTIFY","NAGGED","NAILED","NAILGUN","NAIVELY","NAMELESS","NAMING","NAPOLEON","NARRATED",
    "NARROW","NARROWED","NASAL","NASTIER","NASTINESS","NATIONAL","NATIVELY","NATIVITY","NATURAL",
    "NATURIST","NAUSEATED","NAUTICAL","NAVIGATED","NAVIGATOR","NEARING","NEARLY","NEATNESS",
    "NEBULAR","NECESSARY","NECKED","NECKLACE","NECKTIE","NECROMANCER","NEEDED","NEEDFUL","NEEDLED",
    "NEEDLESS","NEEDLEWORK","NEFARIOUS","NEGATED","NEGATIVE","NEGLIGIBLE","NEGOTIATE","NEIGHBORED",
    "NEIGHBORHOOD","NEIGHED","NESTED","NESTING","NETHERMOST","NETTLED","NETWORKED","NEUTRALIZE",
    "NEVADA","NEWBORN","NEWFOUND","NEWSPAPER","NEWSREEL","NICELY","NICKELED","NIGHTBED","NIGHTCAPS",
    "NIGHTFALL","NIGHTHAWK","NIGHTLIGHT","NIGHTLY","NIGHTMARE","NIGHTSTAND","NIGHTWEAR","NIMBLY",
    "NINETEEN","NINETIES","NINEFOLD","NINETIETH","NIPPED","NITROGEN","NOBILITY","NOBLEMAN",
    "NOCTURNAL","NODDING","NODULES","NOISED","NOISILY","NOISIER","NOMADIC","NOMINAL","NOMINATED",
    "NONCHALANT","NONDESCRIPT","NONFAT","NONFICTIONAL","NONPROFIT","NONSENSE","NONSENSICAL","NONSTOP",
    "NORTHEAST","NORTHERN","NORTHWARD","NOSEBLEED","NOSEDIVE","NOSILY","NOSTALGIC","NOSTRIL",
    "NOTABLE","NOTABLY","NOTARIZE","NOTATIONS","NOTCHED","NOTEBOOK","NOTEPAPER","NOTHING","NOTICED",
    "NOTIFIED","NOTIONAL","NOTORIETY","NOTORIOUS","NOUNED","NOURISHED","NOVELIST","NOVELLA","NOVEMBER",
    "NOWADAYS","NOWHERE","NOXIOUS","NUANCED","NUCLEAR","NUDGED","NUGGETS","NULLIFIED","NUMBERED",
    "NUMERICAL","NUMEROUS","NUMINOUS","NUMSKULL","NUNNERY","NUPTIALS","NURSED","NURTURED","NUTHATCH",
    "NUTRIENTS","NUTRITION","NUTSHELLS","NUZZLED","OAKWOODS","OARSMAN","OBEDIENT","OBELISK","OBESELY",
    "OBEYED","OBEYING","OBFUSCATED","OBITUARY","OBJECTED","OBJECTOR","OBJECTS","OBLATIONS","OBLIGATE",
    "OBLIGED","OBLIQUELY","OBLITERATE","OBLIVIOUS","OBNOXIOUS","OBSCENELY","OBSCURED","OBSERVED",
    "OBSESSED","OBSESSION","OBSOLETE","OBSTACLED","OBSTRUCT","OBTAINED","OBTAINING","OBTRUSIVE",
    "OBVIATE","OBVIOUSLY","OCCASION","OCCLUDED","OCCULTED","OCCUPIED","OCCURRED","OCEANIC",
    "OCTAGONAL","OCTOBER","ODDBALLED","ODDITY","ODORLESS","ODOROUSLY","OFFENDED","OFFENSIVE",
    "OFFERED","OFFERING","OFFHAND","OFFICIAL","OFFICIATE","OFFLOAD","OFFSEASON","OFFSPRING","OFFSTAGE",
    "OFFTRACK","OINTMENTS","OLDFASHIONED","OLDSTERS","OLDTIMERS","OLIGARCHY","OMINOUSLY","OMITTED",
    "OMNIBUSED","OMNIPOTENT","OMNIPRESENT","OMNISCIENT","OMNIVORE","ONBOARD","ONESELF","ONLOOKER",
    "ONRUSHING","ONWARD","OOZED","OOZING","OPENINGS","OPENWORK","OPERABLE","OPERATIC","OPERATED",
    "OPERATING","OPERATION","OPINIONATED","OPPONENT","OPPORTUNE","OPPOSED","OPPRESSED","OPTIMISM",
    "OPTIONAL","ORANGED","ORATIONS","ORATORY","ORBITAL","ORBITED","ORCHARD","ORCHESTRA","ORDAINED",
    "ORDERED","ORDERING","ORDINANCE","ORGANELLE","ORGANIC","ORGANIZED","ORGANIZER","ORIENT",
    "ORIENTAL","ORIENTATED","ORIGINAL","ORIGINATE","ORNAMENTAL","ORNATELY","OSCILLATE","OSTENSIBLY",
    "OSTRICHES","OUTAGED","OUTBURST","OUTCAST","OUTCROP","OUTCRY","OUTDID","OUTDOOR","OUTDREW",
    "OUTFITS","OUTFLANK","OUTFLOW","OUTFOXED","OUTGOING","OUTGREW","OUTHOUSED","OUTLAND","OUTLASTED",
    "OUTLAW","OUTLET","OUTLINED","OUTLIVED","OUTLOOK","OUTLYING","OUTNUMBERED","OUTPATIENT","OUTPLAY",
    "OUTPOST","OUTPOUR","OUTPUT","OUTRAGED","OUTRAN","OUTREACH","OUTRIGGED","OUTRIGHT","OUTRUN",
    "OUTSCORE","OUTSHINE","OUTSHOOT","OUTSIDE","OUTSKIRTS","OUTSMARTED","OUTSPOKEN","OUTSTAYED",
    "OUTSTRETCH","OUTWARD","OUTWEIGH","OUTWITTED","OVATION","OVERATE","OVERBID","OVERBOARD",
    "OVERBOOK","OVERCAME","OVERCAST","OVERCOAT","OVERCOME","OVERDONE","OVERDOSE","OVERDRAW",
    "OVERDRIVE","OVERDUE","OVEREATER","OVERFED","OVERFLOW","OVERGREW","OVERHANG","OVERHAUL","OVERHEAD",
    "OVERHEAR","OVERHEATING","OVERJOY","OVERKILL","OVERLAID","OVERLAND","OVERLAP","OVERLOAD",
    "OVERLOOK","OVERMUCH","OVERNIGHT","OVERPAID","OVERPLAY","OVERRAN","OVERREACT","OVERRIDE","OVERROD",
    "OVERRULE","OVERSAW","OVERSEAS","OVERSEER","OVERSELL","OVERSHADOW","OVERSHOT","OVERSIGHT",
    "OVERSIZED","OVERSLEPT","OVERSTAY","OVERSTEP","OVERTAKE","OVERTAX","OVERTHREW","OVERTHROW",
    "OVERTIME","OVERTONE","OVERTOOK","OVERTURE","OVERTURNED","OVERUSE","OVERVIEW","OVERWORK",
    "OWNERSHIP","OYSTERED","PACIFIED","PACIFIER","PACIFIST","PACIFY","PACKAGED","PACKAGING",
    "PADDOCK","PADLOCK","PAGEANT","PAGINATE","PAINFUL","PAINLESSLY","PAINSTAKING","PAINTERLY",
    "PAIRED","PAIRING","PALACES","PALATIAL","PALATABLE","PALPABLE","PALPITATE","PAMPERED","PANACEAS",
    "PANCAKED","PANDEMIC","PANEGYRIC","PANELED","PANGED","PANICKED","PANORAMIC","PANTING","PAPACY",
    "PAPERBACK","PAPERED","PAPILLA","PARADED","PARADIGM","PARADOX","PARAGRAPH","PARALLEL","PARALYZED",
    "PARAMOUR","PARANOID","PARAPHRASE","PARASITIC","PARCELED","PARCHED","PARCHMENT","PARDONED",
    "PARENTED","PARENTHOOD","PARISHED","PARLAYED","PARLIAMENTARY","PARODIED","PARRIED","PARSED",
    "PARSIMONY","PARTAKEN","PARTERRE","PARTIALLY","PARTICIPATE","PARTICLE","PARTIES","PARTING",
    "PARTITION","PARTNERED","PARTRIDGE","PARTYING","PASSABLE","PASSAGES","PASSED","PASSENGER",
    "PASSIONATE","PASSIVELY","PASSPORT","PASSWORD","PASTORAL","PASTORED","PASTRIES","PASTURING",
    "PATCHED","PATCHWORK","PATERNAL","PATHETIC","PATHFINDER","PATHWAY","PATIENT","PATIENTLY",
    "PATIO","PATRIARCH","PATRIMONY","PATRIOTED","PATRIOTIC","PATROL","PATRONIZE","PATROONED","PATTED",
    "PATTERNED","PAUNCHED","PAUPERED","PAUSED","PAVED","PAVEMENT","PAVILION","PAYABLE","PEACEFUL",
    "PEACETIME","PEAKED","PEALED","PEDDLED","PEDESTAL","PEDIATRIC","PEDIGREED","PEEKED","PEELED",
    "PEEPED","PEERED","PELTED","PENALIZED","PENALTY","PENCILED","PENCHANT","PENDANT","PENDED",
    "PENETRATE","PENINSULAR","PENITENT","PENNANT","PENNILESS","PENNY","PENSIVE","PENTAGON","PEONS",
    "PEOPLED","PEPPERED","PERCEIVED","PERCHED","PERCOLATE","PERFECTED","PERFECTLY","PERFIDIOUS",
    "PERFORMED","PERFUMED","PERHAPS","PERIMETER","PERIODICAL","PERISHED","PERJURED","PERMANENT",
    "PERMEATE","PERMITTED","PERPETRATE","PERPLEXED","PERSIST","PERSONAL","PERSONIFIED","PERSPIRE",
    "PERSUADED","PERTAINED","PERTURB","PERUSED","PERVADED","PERVERSE","PESSIMISM","PESTERED","PESTLE",
    "PETALED","PETITION","PETRIFIED","PETROLEUM","PETTED","PETTING","PHANTOM","PHARMACY","PHENOMENA",
    "PHILANTHROPIC","PHILOSOPHY","PHOENIXED","PHONIED","PHONOGRAPH","PHOSPHATE","PHOTOGRAPH","PHRASES",
    "PHYSICAL","PHYSICIAN","PIANIST","PICKAXE","PICKETED","PICKED","PICKLES","PICKPOCKET","PICKUPS",
    "PICNICKED","PICTURED","PICTURESQUE","PIECED","PIERCED","PIETIES","PIGEONHOLE","PIGLET","PIGMENT",
    "PIGPENS","PIGSTIES","PILLAGED","PILLARS","PILLOWED","PILOTED","PILOTING","PINEAPPLE","PINGPONG",
    "PINIONS","PINKEYE","PINNACLE","PINNED","PIONEERED","PIPED","PIPELINE","PIPING","PIRATED","PISTOLED",
    "PITCHFORK","PITHED","PITIED","PITIFUL","PITTED","PITYING","PIVOTED","PLACARDED","PLACATED",
    "PLACEABLE","PLACED","PLACEHOLDER","PLACEMENT","PLAGIARISM","PLAGUED","PLAINFIELD","PLAINLY",
    "PLAINNESS","PLAITED","PLANES","PLANETOID","PLANKED","PLANNED","PLANTATION","PLANTED","PLASMA",
    "PLASTIC","PLATFORM","PLATINUM","PLATTER","PLAUSIBLE","PLAYED","PLAYHOUSE","PLAYWRIGHT","PLEADED",
    "PLEASANT","PLEASING","PLEDGED","PLENTIFUL","PLEXIGLAS","PLIABLE","PLIGHTED","PLODDED","PLOTTED",
    "PLOUGHED","PLUCKED","PLUGGED","PLUNDER","PLUNGED","PLURALITY","POACHED","POCKETED","POETIC",
    "POIGNANT","POINTING","POINTLESS","POISED","POISONED","POKED","POLARIZED","POLEMICAL","POLICED",
    "POLISHED","POLITELY","POLITICAL","POLLED","POLLUTED","POMPOUS","PONDERED","PONIES","POPSICLE",
    "POPULACE","POPULAR","POPULATE","PORTABLE","PORTAGED","PORTAL","PORTIERE","PORTIONED","PORTLY",
    "PORTRAIT","POSEUR","POSITED","POSITIVE","POSSESSED","POSSESSIVE","POSSIBLE","POSTAGED","POSTCARD",
    "POSTDATE","POSTED","POSTERED","POSTERIOR","POSTHUMOUS","POSTPONE","POSTSCRIPT","POSTULATE",
    "POSTURED","POTABLE","POTENT","POTHOOKS","POTLUCK","POTSHOT","POTTERED","POULTICE","POULTRY",
    "POUNCED","POUNDED","POURED","POUTED","POVERTY","POWDERED","POWERED","POWERLESS","PRACTICAL",
    "PRACTICED","PRAIRIES","PRAISED","PRANCED","PRATED","PRATTLED","PRAYED","PREACHED","PREARRANGE",
    "PRECAUTION","PRECEDED","PRECEPTOR","PRECINCT","PRECIOUS","PRECIPICE","PRECISELY","PRECLUDE",
    "PRECOOK","PREDATED","PREDATOR","PREDICATED","PREDICTED","PREDISPOSE","PREDOMINANT","PREEMPT",
    "PREEXIST","PREFACED","PREFERRED","PREFIGURE","PREGNANT","PREJUDGE","PRELUDED","PREMEDITATE",
    "PREMIERED","PREMIUMS","PREPACKAGE","PREPARED","PREPONDER","PREPOSED","PRESCRIBE","PRESELECT",
    "PRESENTED","PRESERVED","PRESIDED","PRESSED","PRESSURED","PRESTIGE","PRESUMED","PRETENDED",
    "PRETTILY","PRETTY","PREVAILED","PREVENTED","PREVIEWED","PREVIOUSLY","PREYED","PRICED","PRICELESS",
    "PRICKED","PRICKLED","PRIDED","PRIESTED","PRIGGED","PRIMACY","PRIMED","PRIMORDIAL","PRINCELED",
    "PRINCESSED","PRINCIPAL","PRINTED","PRINTING","PRINTOUT","PRIORITIZE","PRIVATE","PRIVATELY",
    "PRIVILEGED","PRIZED","PROCEDURE","PROCESSED","PROCLAIM","PROCLIVE","PROCURED","PRODDED","PRODIGY",
    "PRODUCED","PRODUCER","PROFANED","PROFESSED","PROFICIENT","PROFITED","PROFOUND","PROGRAMMED",
    "PROGRESSED","PROHIBIT","PROJECTED","PROLIFIC","PROLONGED","PROMENADE","PROMINENT","PROMISED",
    "PROMOTED","PROMPTED","PROMULGATE","PRONOUNCED","PROOFED","PROPAGATE","PROPELLED","PROPERLY",
    "PROPERTIED","PROPHESY","PROPOSED","PROPRIETOR","PROSPECT","PROSPERED","PROTECTED","PROTECTOR",
    "PROTESTED","PROTOCOL","PROTOTYPE","PROTRACTED","PROTRUDE","PROUDLY","PROVABLE","PROVENDER",
    "PROVERBED","PROVIDED","PROVIDENT","PROVOKED","PRUNED","PRYING","PUBLICIZED","PUBLISHED",
    "PUDDINGS","PUDDLED","PUFFED","PUGNACIOUS","PULLBACK","PULLED","PULLEY","PULLING","PULPED","PULSE",
    "PULVERIZE","PUMICE","PUMMELED","PUMPED","PUMPING","PUNCHED","PUNCHILY","PUNCTUATED","PUNCTURED",
    "PUNGENT","PUNISHED","PUNISHMENT","PUPPET","PURCHASED","PUREED","PURELY","PURGATIVE","PURIFIED",
    "PURIFIES","PURITAN","PURPLED","PURPOSED","PURSUED","PURSUING","PURVIEW","PUSHED","PUSHCART",
    "PUSHOVER","PUSSYFOOT","PUTREFIED","PUTRESCENT","PUTRID","PUTTERED","PUTTING","PUZZLED","PUZZLING"
  ]}
};

// Fallback to easy if word pool too small
function pickWords(difficulty) {
  const config = WORD_POOLS[difficulty] || WORD_POOLS.average;
  const len = config.length;
  const count = config.count;
  // Filter to actual length match (in case of typos in word list)
  const validWords = config.words.filter(w => w.length === len);
  if (validWords.length < count) {
    console.warn(`Not enough ${len}-letter words in pool. Got ${validWords.length}, need ${count}.`);
  }
  // Shuffle and pick
  const shuffled = [...validWords].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, validWords.length));
}

// ============================================================
// HACK SESSION STATE (one active puzzle)
// ============================================================
const hack = {
  active: false,
  password: null,
  candidates: [],          // current valid candidates (duds get removed)
  attemptsLeft: 4,
  maxAttempts: 4,
  history: [],             // [{guess, score}]
  layout: null,            // generated 2D char array of the screen
  brackets: [],            // {row, startCol, endCol, used}
  wordPositions: [],       // {word, row, startCol, endCol, isDud}
  difficulty: 'average',
  unlockOnWin: null,       // path to unlock when solved (or null)
  onWin: null,             // callback function
  onLose: null,            // callback function
};


// ============================================================
// LAYOUT GENERATION — generates the 32-line screen content
// ============================================================
const JUNK_CHARS = "!@#$%^&*-+=,.;:?/\\|`~";
const BRACKET_PAIRS = [['[',']'], ['{','}'], ['(',')'], ['<','>']];

function generateLayout(words, password) {
  // Two columns of 16 lines, each line has ~12 chars of content + hex address
  const ROWS_PER_COL = 16;
  const CONTENT_PER_LINE = 12;
  const TOTAL_SLOTS = ROWS_PER_COL * 2;

  // Distribute words randomly across the slots
  const wordsToPlace = [...words];
  const slotAssignments = new Array(TOTAL_SLOTS).fill(null);

  // Pick random rows for each word
  const slotIndices = Array.from({length: TOTAL_SLOTS}, (_, i) => i);
  slotIndices.sort(() => Math.random() - 0.5);

  for (let i = 0; i < wordsToPlace.length && i < TOTAL_SLOTS; i++) {
    slotAssignments[slotIndices[i]] = wordsToPlace[i];
  }

  // Build each line's character array
  const layout = [];          // [{leftLine: [...chars], rightLine: [...chars], leftAddr, rightAddr}]
  const wordPositions = [];   // track exact positions of words
  const brackets = [];        // track exact positions of bracket pairs

  // Start with a random base address
  const baseAddr = 0xF000 + Math.floor(Math.random() * 0x0FFF);

  for (let r = 0; r < ROWS_PER_COL; r++) {
    const leftSlot = r;
    const rightSlot = r + ROWS_PER_COL;
    const leftWord = slotAssignments[leftSlot];
    const rightWord = slotAssignments[rightSlot];

    // Build each line
    const leftLine = buildLine(leftWord, CONTENT_PER_LINE, r, 'left', wordPositions);
    const rightLine = buildLine(rightWord, CONTENT_PER_LINE, r, 'right', wordPositions);

    // Find bracket pairs in each line and register them
    findBracketsInLine(leftLine, r, 'left', brackets);
    findBracketsInLine(rightLine, r, 'right', brackets);

    layout.push({
      leftAddr: '0x' + (baseAddr + r * 0x10).toString(16).toUpperCase().padStart(4, '0'),
      rightAddr: '0x' + (baseAddr + (r + ROWS_PER_COL) * 0x10).toString(16).toUpperCase().padStart(4, '0'),
      leftLine,
      rightLine,
    });
  }

  return { layout, wordPositions, brackets };
}

function buildLine(word, length, row, side, wordPositions) {
  // Generate a line with junk; place the word at a random position if there is one
  const chars = [];
  for (let i = 0; i < length; i++) {
    // Sometimes use a bracket char to create potential pairs
    if (Math.random() < 0.20) {
      const pair = BRACKET_PAIRS[Math.floor(Math.random() * BRACKET_PAIRS.length)];
      // Randomly decide open or close
      chars.push(Math.random() < 0.5 ? pair[0] : pair[1]);
    } else {
      chars.push(JUNK_CHARS[Math.floor(Math.random() * JUNK_CHARS.length)]);
    }
  }

  if (word) {
    const startCol = Math.floor(Math.random() * (length - word.length + 1));
    for (let i = 0; i < word.length; i++) {
      chars[startCol + i] = word[i];
    }
    wordPositions.push({
      word,
      row,
      side,
      startCol,
      endCol: startCol + word.length - 1,
      isDud: true,  // will be set to false for password later
    });
  }

  return chars;
}

function findBracketsInLine(lineChars, row, side, brackets) {
  // For each line, find leftmost opening bracket that has a matching closing bracket later
  // Key rule: must NOT have any letters between them (otherwise the word in between is the click target)
  for (let i = 0; i < lineChars.length - 1; i++) {
    const ch = lineChars[i];
    const openIdx = "[{(<".indexOf(ch);
    if (openIdx === -1) continue;

    // Look for the matching closer or any closer of the same family
    const matching = "]})>";
    for (let j = i + 1; j < lineChars.length; j++) {
      // If we hit a letter, this opener doesn't form a bracket pair with anything to its right
      if (/[A-Z]/.test(lineChars[j])) break;
      // Find any closing bracket — game allows mismatched pairs as long as both closes
      if (matching.indexOf(lineChars[j]) !== -1) {
        // Ensure no letters are inside the range
        let hasLetter = false;
        for (let k = i + 1; k < j; k++) {
          if (/[A-Z]/.test(lineChars[k])) { hasLetter = true; break; }
        }
        if (!hasLetter) {
          brackets.push({ row, side, startCol: i, endCol: j, used: false });
          break;  // one bracket per opener
        }
      }
    }
  }
}


// ============================================================
// SCORING — letters in correct position
// ============================================================
function calcLikeness(guess, password) {
  let count = 0;
  for (let i = 0; i < guess.length; i++) {
    if (guess[i] === password[i]) count++;
  }
  return count;
}


// ============================================================
// RENDERING — draw the puzzle to the screen
// ============================================================
function renderHackScreen() {
  const screen = document.getElementById("screen-content");
  if (!screen) return;
  screen.innerHTML = "";

  // Header
  const header = document.createElement("div");
  header.className = "hack-header";
  header.innerHTML = `ROBCO INDUSTRIES (TM) TERMLINK PROTOCOL<br>
ENTER PASSWORD NOW<br><br>
<span class="hack-attempts">${hack.attemptsLeft} ATTEMPT(S) LEFT: ${'■ '.repeat(hack.attemptsLeft).trim()}</span><br><br>`;
  screen.appendChild(header);

  // Two-column body
  const body = document.createElement("div");
  body.className = "hack-body";

  for (let r = 0; r < hack.layout.length; r++) {
    const row = hack.layout[r];
    const rowDiv = document.createElement("div");
    rowDiv.className = "hack-row";
    rowDiv.innerHTML = `<span class="hack-addr">${row.leftAddr}</span> <span class="hack-line" data-row="${r}" data-side="left">${renderLine(row.leftLine, r, 'left')}</span> &nbsp;&nbsp; <span class="hack-addr">${row.rightAddr}</span> <span class="hack-line" data-row="${r}" data-side="right">${renderLine(row.rightLine, r, 'right')}</span>`;
    body.appendChild(rowDiv);
  }

  screen.appendChild(body);

  // History panel
  const history = document.createElement("div");
  history.className = "hack-history";
  let historyHTML = '<div class="hack-history-title">&gt; HISTORY</div>';
  if (hack.history.length === 0) {
    historyHTML += '<div class="hack-history-empty">(no attempts yet)</div>';
  } else {
    for (let i = hack.history.length - 1; i >= 0; i--) {
      const h = hack.history[i];
      historyHTML += `<div>&gt; ${h.guess}<br>&gt; ${h.score === 'OK' ? 'Entry granted.' : `${h.score}/${hack.password.length} correct.`}</div>`;
    }
  }
  history.innerHTML = historyHTML;
  screen.appendChild(history);

  // Hint footer
  const hint = document.createElement("div");
  hint.className = "hack-hint";
  hint.innerHTML = `<br>Click a word to guess, or click a [matched] bracket pair for a bonus.<br>Type the word and press Enter to guess. Type 'cancel' or press Esc to abort.`;
  screen.appendChild(hint);

  // Wire up clicks
  attachHackClickHandlers();

  screen.scrollTop = screen.scrollHeight;
}


function renderLine(lineChars, row, side) {
  // Convert a line of chars into HTML with clickable word/bracket spans
  let html = '';
  let i = 0;

  // Build word positions and bracket positions for this specific row+side
  const wordsHere = hack.wordPositions.filter(w => w.row === row && w.side === side);
  const bracketsHere = hack.brackets.filter(b => b.row === row && b.side === side);

  while (i < lineChars.length) {
    // Check if we're at the start of a word
    const wordHere = wordsHere.find(w => w.startCol === i);
    if (wordHere && hack.candidates.includes(wordHere.word)) {
      const word = wordHere.word;
      // Each letter gets its own span for individual hover highlight
      // Parent span gets word-level hover treatment via JS mouseenter/leave
      const letterSpans = word.split("").map(ch =>
        `<span class="hack-letter">${escapeHtml(ch)}</span>`
      ).join("");
      html += `<span class="hack-word" data-word="${word}">${letterSpans}</span>`;
      i += word.length;
      continue;
    }
    // Check if we're at the start of a bracket pair (not used)
    const bracketHere = bracketsHere.find(b => b.startCol === i && !b.used);
    if (bracketHere) {
      const segment = lineChars.slice(bracketHere.startCol, bracketHere.endCol + 1).join('');
      // Each char in the bracket pair gets its own span too
      const charSpans = segment.split("").map(ch =>
        `<span class="hack-bracket-char">${escapeHtml(ch)}</span>`
      ).join("");
      html += `<span class="hack-bracket" data-row="${row}" data-side="${side}" data-start="${bracketHere.startCol}">${charSpans}</span>`;
      i = bracketHere.endCol + 1;
      continue;
    }
    // Default: render single char (could be a removed dud's blanked space or junk)
    const wordOverlap = wordsHere.find(w => i >= w.startCol && i <= w.endCol);
    if (wordOverlap && !hack.candidates.includes(wordOverlap.word)) {
      // Dud has been removed — replace word's letters with a dot
      html += '.';
      i++;
      continue;
    }
    html += escapeHtml(lineChars[i]);
    i++;
  }

  return html;
}


function escapeHtml(s) {
  return String(s).replace(/[<>&"']/g, c => ({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&#39;'}[c]));
}


function attachHackClickHandlers() {
  // Words
  document.querySelectorAll('.hack-word').forEach(el => {
    el.addEventListener('click', () => {
      const word = el.dataset.word;
      if (word) submitGuess(word);
    });
    el.addEventListener('mouseenter', () => el.classList.add('hover'));
    el.addEventListener('mouseleave', () => el.classList.remove('hover'));
  });
  // Brackets
  document.querySelectorAll('.hack-bracket').forEach(el => {
    el.addEventListener('click', () => {
      const row = parseInt(el.dataset.row);
      const side = el.dataset.side;
      const start = parseInt(el.dataset.start);
      activateBracket(row, side, start);
    });
    el.addEventListener('mouseenter', () => el.classList.add('hover'));
    el.addEventListener('mouseleave', () => el.classList.remove('hover'));
  });
}


// ============================================================
// GUESSING / BRACKETS / WIN / LOSE
// ============================================================
function submitGuess(word) {
  if (!hack.active) return;
  word = word.toUpperCase();
  if (!hack.candidates.includes(word)) {
    // Show feedback that it's not a valid choice
    flashScreenMessage(`> ${word}\n> Not a valid candidate.`);
    return;
  }

  const score = calcLikeness(word, hack.password);

  if (word === hack.password) {
    hack.history.push({ guess: word, score: 'OK' });
    renderHackScreen();
    setTimeout(() => winHack(), 800);
    return;
  }

  hack.history.push({ guess: word, score });
  hack.attemptsLeft--;

  // Remove the wrong word from candidates
  hack.candidates = hack.candidates.filter(c => c !== word);

  if (hack.attemptsLeft <= 0) {
    renderHackScreen();
    setTimeout(() => loseHack(), 800);
    return;
  }

  renderHackScreen();
}


function activateBracket(row, side, start) {
  if (!hack.active) return;
  const b = hack.brackets.find(x => x.row === row && x.side === side && x.startCol === start);
  if (!b || b.used) return;

  // Game rule: if only one candidate left, "Entry Denied" (no effect)
  if (hack.candidates.length <= 1) {
    flashScreenMessage('> Entry Denied.');
    return;
  }

  b.used = true;

  // 50/50: dud removal or attempts replenish (game-canonical behavior)
  // Slightly weighted toward dud removal since that's more common in the game
  const replenish = Math.random() < 0.30;

  if (replenish) {
    hack.attemptsLeft = hack.maxAttempts;
    flashScreenMessage('> Allowance Replenished.');
  } else {
    // Pick a random non-password candidate to remove
    const duds = hack.candidates.filter(c => c !== hack.password);
    if (duds.length > 0) {
      const removed = duds[Math.floor(Math.random() * duds.length)];
      hack.candidates = hack.candidates.filter(c => c !== removed);
      flashScreenMessage(`> Dud Removed.`);
    } else {
      flashScreenMessage('> Entry Denied.');
    }
  }
  setTimeout(() => renderHackScreen(), 500);
}


function flashScreenMessage(msg) {
  const screen = document.getElementById("screen-content");
  if (!screen) return;
  const div = document.createElement("div");
  div.className = "hack-flash";
  div.textContent = msg;
  screen.appendChild(div);
  screen.scrollTop = screen.scrollHeight;
  setTimeout(() => { if (div.parentElement) div.remove(); }, 2000);
}


function winHack() {
  hack.active = false;
  const screen = document.getElementById("screen-content");
  screen.innerHTML = '';
  const div = document.createElement("div");
  div.className = "line line-bright";
  div.innerHTML = `<br><br>> EXACT MATCH!<br>> PLEASE WAIT WHILE SYSTEM IS ACCESSED.<br><br>> ACCESS GRANTED.<br>`;
  screen.appendChild(div);

  // Optional unlock
  if (hack.unlockOnWin && window.UNLOCKED_FILES) {
    window.UNLOCKED_FILES.add(hack.unlockOnWin);
    const unlockDiv = document.createElement("div");
    unlockDiv.className = "line line-bright";
    unlockDiv.innerHTML = `<br>> File unlocked: ${hack.unlockOnWin}<br>> Use 'read ${hack.unlockOnWin}' to view contents.<br>`;
    screen.appendChild(unlockDiv);
  }

  setTimeout(() => {
    if (window.terminal) window.terminal.showPrompt();
    if (hack.onWin) hack.onWin();
  }, 1800);
}


function loseHack() {
  hack.active = false;
  const screen = document.getElementById("screen-content");
  screen.innerHTML = '';
  const div = document.createElement("div");
  div.className = "line line-error";
  div.innerHTML = `<br><br>> TERMINAL LOCKED OUT<br>> PLEASE CONTACT AN ADMINISTRATOR.<br><br>> The password was: ${hack.password}<br>`;
  screen.appendChild(div);
  setTimeout(() => {
    if (window.terminal) window.terminal.showPrompt();
    if (hack.onLose) hack.onLose();
  }, 2000);
}


// ============================================================
// PUBLIC API — start a hack
// ============================================================
function startHack(options = {}) {
  const difficulty = options.difficulty || 'average';
  const config = WORD_POOLS[difficulty];
  if (!config) {
    return { error: `Unknown difficulty: ${difficulty}. Try: very_easy, easy, average, hard.` };
  }

  const words = pickWords(difficulty);
  if (words.length === 0) {
    return { error: "Couldn't generate puzzle words." };
  }

  const password = words[Math.floor(Math.random() * words.length)];
  const { layout, wordPositions, brackets } = generateLayout(words, password);

  // Mark the password word
  for (const wp of wordPositions) {
    if (wp.word === password) wp.isDud = false;
  }

  hack.active = true;
  hack.password = password;
  hack.candidates = [...words];
  hack.attemptsLeft = 4;
  hack.maxAttempts = 4;
  hack.history = [];
  hack.layout = layout;
  hack.wordPositions = wordPositions;
  hack.brackets = brackets;
  hack.difficulty = difficulty;
  hack.unlockOnWin = options.unlockOnWin || null;
  hack.onWin = options.onWin || null;
  hack.onLose = options.onLose || null;

  // Keep the prompt visible during the puzzle so the user can type guesses
  // (the prompt-path will show the difficulty for context)
  const pathEl = document.getElementById("prompt-path");
  if (pathEl) pathEl.textContent = `[hack:${difficulty}]`;

  renderHackScreen();
  return { ok: true };
}


function cancelHack() {
  if (!hack.active) return;
  hack.active = false;
  if (window.terminal) window.terminal.showPrompt();
}


// Make available globally
window.startHack = startHack;
window.cancelHack = cancelHack;
window.hackState = hack;
window.submitHackGuess = submitGuess;

// Track unlocked files (for filesystem locking)
if (!window.UNLOCKED_FILES) {
  window.UNLOCKED_FILES = new Set();
}
